In [12]:
import pandas as pd
from pathlib import Path
import glob

In [33]:
data_path = "/Users/meeratrivedi/Downloads/STAT 390/data"

## Data Import Code

In [34]:
folder = Path(data_path)
files = sorted(list(folder.glob("*.csv")) + list(folder.glob("*.xlsx")))
df_main = pd.DataFrame(columns=['Contact Session ID', 'EP Name', 'Flow Name', 'Activity Name', 'Activity Start Timestamp', 
                                'Queue Name', 'Agent Name', 'Termination Reason'])
df_main

Empty DataFrame
Columns: [Contact Session ID, EP Name, Flow Name, Activity Name, Activity Start Timestamp, Queue Name, Agent Name, Termination Reason]
Index: []

In [35]:
i=0
for f in files:
    i = i + 1
    if f.suffix.lower() == ".csv":
        df = pd.read_csv(f, header=2, dtype=str, engine="python", skip_blank_lines=False)
    else:  # .xlsx
        df = pd.read_excel(f, sheet_name=0, header=2, dtype=str)
    df_main = pd.concat([df_main, df], ignore_index=True)
    print(i, f.stem, df.shape)

1 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 3-16 to 3-22-25 (45326, 8)
2 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 3-30 to 4-5-25 (45072, 8)

In [36]:
df_main["Activity Start Timestamp"] = pd.to_datetime(df_main["Activity Start Timestamp"], errors="coerce")
# Creating a new column 'hour' as it will be useful to visualize peak calling hours
df_main["hour"] = df_main["Activity Start Timestamp"].dt.hour
df_main["weekday"] = df_main["Activity Start Timestamp"].dt.day_name()

/var/folders/vr/tdmh9w694nx9v20sfh47x4tr0000gn/T/ipykernel_63665/3439861526.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_main["Activity Start Timestamp"] = pd.to_datetime(df_main["Activity Start Timestamp"], errors="coerce")

In [38]:
df_main.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90398 entries, 0 to 90397
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Contact Session ID        90398 non-null  object
 1   EP Name                   68092 non-null  object
 2   Flow Name                 24796 non-null  object
 3   Activity Name             40484 non-null  object
 4   Activity Start Timestamp  90398 non-null  datetime64[ns]
 5   Queue Name                12355 non-null  object
 6   Agent Name                9002 non-null   object
 7   Termination Reason        7605 non-null   object
 8   hour                      90398 non-null  int32
 9   weekday                   90398 non-null  object
dtypes: datetime64[ns](1), int32(1), object(8)
memory usage: 6.6+ MB

In [39]:
df_main.head(10)

,Contact Session ID,EP Name,Flow Name,Activity Name,Activity Start Timestamp,Queue Name,Agent Name,Termination Reason,hour,weekday
0,ced63a4a-89f4-4e11-94b3-447a01cd34cb,Main Number Telephony EP,NaN,NaN,2025-03-16 00:40:10,NaN,NaN,NaN,0,Sunday
1,ced63a4a-89f4-4e11-94b3-447a01cd34cb,NaN,LACMain,NaN,2025-03-16 00:40:10,NaN,NaN,NaN,0,Sunday
2,ced63a4a-89f4-4e11-94b3-447a01cd34cb,Main Number Telephony EP,NaN,LanguageSelectionMenu,2025-03-16 00:40:10,NaN,NaN,NaN,0,Sunday
3,ced63a4a-89f4-4e11-94b3-447a01cd34cb,Main Number Telephony EP,LACMain,NaN,2025-03-16 00:40:10,NaN,NaN,NaN,0,Sunday
4,ced63a4a-89f4-4e11-94b3-447a01cd34cb,Main Number Telephony EP,NaN,NaN,2025-03-16 00:40:12,NaN,NaN,Customer Left,0,Sunday
5,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,NaN,NaN,NaN,2025-03-16 02:15:16,Consumer SP,NaN,Queue Timeout,2,Sunday
6,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,NaN,NaN,NaN,2025-03-16 02:15:16,Consumer SP,NaN,Customer Left,2,Sunday
7,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,Courtesy Callback Telephony EP,NaN,CallbackRetry,2025-03-16 02:15:26,NaN,NaN,NaN,2,Sunday
8,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,NaN,NaN,NaN,2025-03-16 02:15:26,Consumer SP,NaN,NaN,2,Sunday
9,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,NaN,NaN,NaN,2025-03-16 02:15:26,Consumer SP,NaN,Customer Left,2,Sunday

## Data Cleaning

In [41]:
##Customer Left

customer_left = df_main[df_main['Termination Reason'] == 'Customer Left']

customer_left.head(10)

,Contact Session ID,EP Name,Flow Name,Activity Name,Activity Start Timestamp,Queue Name,Agent Name,Termination Reason,hour,weekday
4,ced63a4a-89f4-4e11-94b3-447a01cd34cb,Main Number Telephony EP,NaN,NaN,2025-03-16 00:40:12,NaN,NaN,Customer Left,0,Sunday
6,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,NaN,NaN,NaN,2025-03-16 02:15:16,Consumer SP,NaN,Customer Left,2,Sunday
9,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,NaN,NaN,NaN,2025-03-16 02:15:26,Consumer SP,NaN,Customer Left,2,Sunday
10,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,Courtesy Callback Telephony EP,NaN,NaN,2025-03-16 02:15:26,Consumer SP,NaN,Customer Left,2,Sunday
24,1b35074f-6d8b-4132-99a2-32ae83ea54cf,Closed Hours-Holidays Menu Telephony EP,NaN,NaN,2025-03-16 02:42:18,Staff Directory English Transfer,CBT Agent,Customer Left,2,Sunday
36,6364de29-c942-4e6f-95fe-4a63ee631450,Farmworker Main Number Telephony EP,NaN,NaN,2025-03-16 07:51:33,NaN,NaN,Customer Left,7,Sunday
47,2cf62d7e-60f7-4ea9-86c4-24583bd96baa,Main Number Telephony EP,LACMain,NaN,2025-03-16 08:21:15,NaN,NaN,Customer Left,8,Sunday
48,2cf62d7e-60f7-4ea9-86c4-24583bd96baa,Main Number Telephony EP,NaN,NaN,2025-03-16 08:21:15,NaN,NaN,Customer Left,8,Sunday
54,c12bfc6c-1bf8-4203-a1cf-df4106cc252f,Farmworker Main Number Telephony EP,NaN,NaN,2025-03-16 08:30:32,NaN,NaN,Customer Left,8,Sunday
60,133abc79-dcd0-4331-8305-6a8ec3fcf97f,Farmworker Main Number Telephony EP,NaN,NaN,2025-03-16 08:55:12,NaN,NaN,Customer Left,8,Sunday

In [86]:
#Inner join
calls_customer_left = df_main[df_main["Contact Session ID"].isin(customer_left["Contact Session ID"])].copy()

#Give each session ID an ID number in order of appearance
calls_customer_left["Call ID"] = calls_customer_left["Contact Session ID"].map(
    {id_: i+1 for i, id_ in enumerate(calls_customer_left["Contact Session ID"].unique())}
)

#Calculate Time Difference between rows 
calls_customer_left["Time Difference"] = (
    calls_customer_left.groupby("Contact Session ID")["Activity Start Timestamp"]
    .diff()
    .dt.total_seconds()  
)

calls_customer_left = calls_customer_left[
    [
        'Call ID',
        'Contact Session ID',
        'EP Name',
        'Flow Name',
        'Activity Name',
        'Queue Name',
        'Termination Reason',
        'Activity Start Timestamp',
        'Time Difference', #seconds
        'weekday', 
    ]
]

calls_customer_left.head(5)

,Call ID,Contact Session ID,EP Name,Flow Name,Activity Name,Queue Name,Termination Reason,Activity Start Timestamp,Time Difference,weekday
0,1,ced63a4a-89f4-4e11-94b3-447a01cd34cb,Main Number Telephony EP,NaN,NaN,NaN,NaN,2025-03-16 00:40:10,NaN,Sunday
1,1,ced63a4a-89f4-4e11-94b3-447a01cd34cb,NaN,LACMain,NaN,NaN,NaN,2025-03-16 00:40:10,0.0,Sunday
2,1,ced63a4a-89f4-4e11-94b3-447a01cd34cb,Main Number Telephony EP,NaN,LanguageSelectionMenu,NaN,NaN,2025-03-16 00:40:10,0.0,Sunday
3,1,ced63a4a-89f4-4e11-94b3-447a01cd34cb,Main Number Telephony EP,LACMain,NaN,NaN,NaN,2025-03-16 00:40:10,0.0,Sunday
4,1,ced63a4a-89f4-4e11-94b3-447a01cd34cb,Main Number Telephony EP,NaN,NaN,NaN,Customer Left,2025-03-16 00:40:12,2.0,Sunday

## Example 1: Customer Left after long wait time

#### On FarmworkerMainMenu and left after 24 minutes.

In [82]:
calls_customer_left[calls_customer_left["Call ID"] == 4]

,Call ID,Contact Session ID,EP Name,Flow Name,Activity Name,Queue Name,Termination Reason,Activity Start Timestamp,Time Difference,weekday
31,4,6364de29-c942-4e6f-95fe-4a63ee631450,Farmworker Main Number Telephony EP,NaN,NaN,NaN,NaN,2025-03-16 07:27:28,NaN,Sunday
32,4,6364de29-c942-4e6f-95fe-4a63ee631450,NaN,FarmworkerMain,NaN,NaN,NaN,2025-03-16 07:27:28,0.0,Sunday
33,4,6364de29-c942-4e6f-95fe-4a63ee631450,Farmworker Main Number Telephony EP,NaN,LanguageSelectionMenu,NaN,NaN,2025-03-16 07:27:28,0.0,Sunday
34,4,6364de29-c942-4e6f-95fe-4a63ee631450,Farmworker Main Number Telephony EP,FarmworkerMain,NaN,NaN,NaN,2025-03-16 07:27:28,0.0,Sunday
35,4,6364de29-c942-4e6f-95fe-4a63ee631450,Farmworker Main Number Telephony EP,NaN,FarmworkerMainMenu,NaN,NaN,2025-03-16 07:27:36,8.0,Sunday
36,4,6364de29-c942-4e6f-95fe-4a63ee631450,Farmworker Main Number Telephony EP,NaN,NaN,NaN,Customer Left,2025-03-16 07:51:33,1437.0,Sunday

#### On FarmworkerMainMenu and left after 30 minutes.

In [83]:
calls_customer_left[calls_customer_left["Call ID"] == 7]

,Call ID,Contact Session ID,EP Name,Flow Name,Activity Name,Queue Name,Termination Reason,Activity Start Timestamp,Time Difference,weekday
49,7,133abc79-dcd0-4331-8305-6a8ec3fcf97f,Farmworker Main Number Telephony EP,NaN,NaN,NaN,NaN,2025-03-16 08:25:40,NaN,Sunday
50,7,133abc79-dcd0-4331-8305-6a8ec3fcf97f,NaN,FarmworkerMain,NaN,NaN,NaN,2025-03-16 08:25:40,0.0,Sunday
51,7,133abc79-dcd0-4331-8305-6a8ec3fcf97f,Farmworker Main Number Telephony EP,NaN,LanguageSelectionMenu,NaN,NaN,2025-03-16 08:25:40,0.0,Sunday
52,7,133abc79-dcd0-4331-8305-6a8ec3fcf97f,Farmworker Main Number Telephony EP,FarmworkerMain,NaN,NaN,NaN,2025-03-16 08:25:40,0.0,Sunday
53,7,133abc79-dcd0-4331-8305-6a8ec3fcf97f,Farmworker Main Number Telephony EP,NaN,FarmworkerMainMenu,NaN,NaN,2025-03-16 08:25:48,8.0,Sunday
60,7,133abc79-dcd0-4331-8305-6a8ec3fcf97f,Farmworker Main Number Telephony EP,NaN,NaN,NaN,Customer Left,2025-03-16 08:55:12,1764.0,Sunday

#### On FarmworkerMainMenu and left after 30 minutes.

In [84]:
calls_customer_left[calls_customer_left["Call ID"] == 8]

,Call ID,Contact Session ID,EP Name,Flow Name,Activity Name,Queue Name,Termination Reason,Activity Start Timestamp,Time Difference,weekday
55,8,1431554c-6f53-4904-af0a-57026f554d40,Farmworker Main Number Telephony EP,NaN,NaN,NaN,NaN,2025-03-16 08:30:39,NaN,Sunday
56,8,1431554c-6f53-4904-af0a-57026f554d40,NaN,FarmworkerMain,NaN,NaN,NaN,2025-03-16 08:30:39,0.0,Sunday
57,8,1431554c-6f53-4904-af0a-57026f554d40,Farmworker Main Number Telephony EP,NaN,LanguageSelectionMenu,NaN,NaN,2025-03-16 08:30:39,0.0,Sunday
58,8,1431554c-6f53-4904-af0a-57026f554d40,Farmworker Main Number Telephony EP,FarmworkerMain,NaN,NaN,NaN,2025-03-16 08:30:39,0.0,Sunday
59,8,1431554c-6f53-4904-af0a-57026f554d40,Farmworker Main Number Telephony EP,NaN,FarmworkerMainMenu,NaN,NaN,2025-03-16 08:30:47,8.0,Sunday
61,8,1431554c-6f53-4904-af0a-57026f554d40,Farmworker Main Number Telephony EP,NaN,NaN,NaN,Customer Left,2025-03-16 09:00:06,1759.0,Sunday

## Example 2: Customer Left during Courtesy Callback

#### Rows 10 and 255: Customer Left during Courtesy Callback Telephone EP.

In [91]:
calls_customer_left[
    (calls_customer_left["Call ID"] == 2) &
    (calls_customer_left["weekday"] == "Sunday")
]

,Call ID,Contact Session ID,EP Name,Flow Name,Activity Name,Queue Name,Termination Reason,Activity Start Timestamp,Time Difference,weekday
5,2,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,NaN,NaN,NaN,Consumer SP,Queue Timeout,2025-03-16 02:15:16,NaN,Sunday
6,2,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,NaN,NaN,NaN,Consumer SP,Customer Left,2025-03-16 02:15:16,0.0,Sunday
7,2,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,Courtesy Callback Telephony EP,NaN,CallbackRetry,NaN,NaN,2025-03-16 02:15:26,10.0,Sunday
8,2,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,NaN,NaN,NaN,Consumer SP,NaN,2025-03-16 02:15:26,0.0,Sunday
9,2,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,NaN,NaN,NaN,Consumer SP,Customer Left,2025-03-16 02:15:26,0.0,Sunday
10,2,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,Courtesy Callback Telephony EP,NaN,NaN,Consumer SP,Customer Left,2025-03-16 02:15:26,0.0,Sunday
246,2,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,NaN,NaN,NaN,Consumer SP,Customer Left,2025-03-16 23:15:26,75600.0,Sunday
247,2,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,NaN,NaN,NaN,Consumer SP,Queue Timeout,2025-03-16 23:15:26,0.0,Sunday
252,2,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,Courtesy Callback Telephony EP,NaN,CallbackRetry,NaN,NaN,2025-03-16 23:15:36,10.0,Sunday
253,2,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,NaN,NaN,NaN,Consumer SP,NaN,2025-03-16 23:15:36,0.0,Sunday
254,2,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,NaN,NaN,NaN,Consumer SP,Customer Left,2025-03-16 23:15:36,0.0,Sunday
255,2,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,Courtesy Callback Telephony EP,NaN,NaN,Consumer SP,Customer Left,2025-03-16 23:15:36,0.0,Sunday

#### Rows 397, 413 and 692: Customer Left during Courtesy Callback Telephone EP.

In [92]:
calls_customer_left[
    (calls_customer_left["Call ID"] == 2) &
    (calls_customer_left["weekday"] == "Monday")
]

,Call ID,Contact Session ID,EP Name,Flow Name,Activity Name,Queue Name,Termination Reason,Activity Start Timestamp,Time Difference,weekday
397,2,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,Courtesy Callback Telephony EP,NaN,NaN,Consumer SP,Customer Left,2025-03-17 08:00:57,31521.0,Monday
398,2,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,Courtesy Callback Telephony EP,NaN,LegalServerScreenPop,NaN,NaN,2025-03-17 08:00:59,2.0,Monday
413,2,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,Courtesy Callback Telephony EP,NaN,NaN,Consumer SP,Customer Left,2025-03-17 08:01:24,25.0,Monday
692,2,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,Courtesy Callback Telephony EP,NaN,NaN,Consumer SP,Customer Left,2025-03-17 08:10:06,522.0,Monday
693,2,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,NaN,NaN,NaN,Consumer SP,NaN,2025-03-17 08:10:06,0.0,Monday
784,2,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,NaN,NaN,NaN,Consumer SP,NaN,2025-03-17 08:12:06,120.0,Monday

#### Row 40486: There was 1 hour and 17 minutes between the last activity and the customer leaving; customer left during courtesy callback.

In [97]:
calls_customer_left[calls_customer_left["Call ID"] == 2354]

,Call ID,Contact Session ID,EP Name,Flow Name,Activity Name,Queue Name,Termination Reason,Activity Start Timestamp,Time Difference,weekday
39465,2354,3938eae0-a575-408b-9dfc-c41e107835ed,Main Number Telephony EP,NaN,NaN,NaN,NaN,2025-03-21 10:05:40,NaN,Friday
39466,2354,3938eae0-a575-408b-9dfc-c41e107835ed,NaN,LACMain,NaN,NaN,NaN,2025-03-21 10:05:40,0.0,Friday
39467,2354,3938eae0-a575-408b-9dfc-c41e107835ed,Main Number Telephony EP,NaN,LanguageSelectionMenu,NaN,NaN,2025-03-21 10:05:40,0.0,Friday
39468,2354,3938eae0-a575-408b-9dfc-c41e107835ed,Main Number Telephony EP,LACMain,NaN,NaN,NaN,2025-03-21 10:05:40,0.0,Friday
39476,2354,3938eae0-a575-408b-9dfc-c41e107835ed,Main Number Telephony EP,NaN,MainMenu,NaN,NaN,2025-03-21 10:05:53,13.0,Friday
39482,2354,3938eae0-a575-408b-9dfc-c41e107835ed,Main Number Telephony EP,NaN,AppointmentMenu,NaN,NaN,2025-03-21 10:06:30,37.0,Friday
39484,2354,3938eae0-a575-408b-9dfc-c41e107835ed,NaN,PreLegalMenuSeniorsMenu,NaN,NaN,NaN,2025-03-21 10:06:39,9.0,Friday
39485,2354,3938eae0-a575-408b-9dfc-c41e107835ed,Pre-Legal Menu Seniors Menu Telephony EP,NaN,SeniorsMenu,NaN,NaN,2025-03-21 10:06:39,0.0,Friday
39486,2354,3938eae0-a575-408b-9dfc-c41e107835ed,Pre-Legal Menu Seniors Menu Telephony EP,NaN,SeniorsConfirmationMenu,NaN,NaN,2025-03-21 10:06:49,10.0,Friday
39490,2354,3938eae0-a575-408b-9dfc-c41e107835ed,Pre-Legal Menu Seniors Menu Telephony EP,NaN,SuburbsOrCityMenu,NaN,NaN,2025-03-21 10:07:05,16.0,Friday
39511,2354,3938eae0-a575-408b-9dfc-c41e107835ed,Pre-Legal Menu Seniors Menu Telephony EP,NaN,SuburbanSeniorsMenu,NaN,NaN,2025-03-21 10:07:26,21.0,Friday
39546,2354,3938eae0-a575-408b-9dfc-c41e107835ed,NaN,Queues,NaN,NaN,NaN,2025-03-21 10:08:48,82.0,Friday
39547,2354,3938eae0-a575-408b-9dfc-c41e107835ed,All LAC Queues Telephony EP,NaN,GetLoggedInSubSeniorFamilyAgents,NaN,NaN,2025-03-21 10:08:48,0.0,Friday
39548,2354,3938eae0-a575-408b-9dfc-c41e107835ed,All LAC Queues Telephony EP,NaN,SubSeniorPreQueueMessage1_1,NaN,NaN,2025-03-21 10:08:48,0.0,Friday
39562,2354,3938eae0-a575-408b-9dfc-c41e107835ed,All LAC Queues Telephony EP,NaN,SubSeniorFamilyQueue,NaN,NaN,2025-03-21 10:09:45,57.0,Friday
39563,2354,3938eae0-a575-408b-9dfc-c41e107835ed,NaN,NaN,NaN,SubSenior Family,NaN,2025-03-21 10:09:45,0.0,Friday
39564,2354,3938eae0-a575-408b-9dfc-c41e107835ed,All LAC Queues Telephony EP,NaN,NaN,NaN,NaN,2025-03-21 10:09:45,0.0,Friday
39565,2354,3938eae0-a575-408b-9dfc-c41e107835ed,All LAC Queues Telephony EP,NaN,NaN,SubSenior Family,NaN,2025-03-21 10:09:45,0.0,Friday
39566,2354,3938eae0-a575-408b-9dfc-c41e107835ed,All LAC Queues Telephony EP,NaN,PreQueueMessage2,NaN,NaN,2025-03-21 10:09:45,0.0,Friday
39567,2354,3938eae0-a575-408b-9dfc-c41e107835ed,All LAC Queues Telephony EP,NaN,PlayMOH300s,NaN,NaN,2025-03-21 10:09:57,12.0,Friday
39676,2354,3938eae0-a575-408b-9dfc-c41e107835ed,All LAC Queues Telephony EP,NaN,QueueMenu1,NaN,NaN,2025-03-21 10:14:58,301.0,Friday
39680,2354,3938eae0-a575-408b-9dfc-c41e107835ed,NaN,CourtesyCallback,NaN,NaN,NaN,2025-03-21 10:15:13,15.0,Friday
39681,2354,3938eae0-a575-408b-9dfc-c41e107835ed,Courtesy Callback Telephony EP,NaN,ReadANI,NaN,NaN,2025-03-21 10:15:13,0.0,Friday
39692,2354,3938eae0-a575-408b-9dfc-c41e107835ed,Courtesy Callback Telephony EP,NaN,CCB,NaN,NaN,2025-03-21 10:15:28,15.0,Friday
39693,2354,3938eae0-a575-408b-9dfc-c41e107835ed,NaN,NaN,NaN,SubSenior Family,NaN,2025-03-21 10:15:28,0.0,Friday
39694,2354,3938eae0-a575-408b-9dfc-c41e107835ed,Courtesy Callback Telephony EP,NaN,PlayCCBConfirmation,NaN,NaN,2025-03-21 10:15:28,0.0,Friday
39700,2354,3938eae0-a575-408b-9dfc-c41e107835ed,Courtesy Callback Telephony EP,NaN,DisconnectContact1,NaN,NaN,2025-03-21 10:15:38,10.0,Friday
40486,2354,3938eae0-a575-408b-9dfc-c41e107835ed,Courtesy Callback Telephony EP,NaN,NaN,SubSenior Family,Customer Left,2025-03-21 11:22:56,4038.0,Friday
40487,2354,3938eae0-a575-408b-9dfc-c41e107835ed,Courtesy Callback Telephony EP,NaN,LegalServerScreenPop,NaN,NaN,2025-03-21 11:22:56,0.0,Friday
40495,2354,3938eae0-a575-408b-9dfc-c41e107835ed,Courtesy Callback Telephony EP,NaN,NaN,SubSenior Family,RONA_TIMER_EXPIRED,2025-03-21 11:23:11,15.0,Friday
40496,2354,3938eae0-a575-408b-9dfc-c41e107835ed,Courtesy Callback Telephony EP,NaN,NaN,SubSenior Family,RONA Timer Expired,2025-03-21 11:23:11,0.0,Friday
40512,2354,3938eae0-a575-408b-9dfc-c41e107835ed,Courtesy Callback Telephony EP,NaN,NaN,SubSenior Family,RONA Timer Expired,2025-03-21 11:23:52,41.0,Friday
40513,2354,3938eae0-a575-408b-9dfc-c41e107835ed,Courtesy Callback Telephony EP,NaN,LegalServerScreenPop,NaN,NaN,2025-03-21 11:23:53,1.0,Friday
40520,2354,3938eae0-a575-408b-9dfc-c41e107835ed,Courtesy Callback Telephony EP,NaN,NaN,SubSenior Family,RONA Timer Expired,2025-03-21 11:24:14,21.0,Friday
40553,2354,3938eae0-a575-408b-9dfc-c41e107835ed,Courtesy Callback Telephony EP,NaN,NaN,SubSenior Family,Agent Left,2025-03-21 11:26:00,106.0,Friday
40554,2354,3938eae0-a575-408b-9dfc-c41e107835ed,NaN,NaN,NaN,SubSenior Family,NaN,2025-03-21 11:26:00,0.0,Friday
40555,2354,3938eae0-a575-408b-9dfc-c41e107835ed,NaN,NaN,NaN,SubSenior Family,NaN,2025-03-21 11:26:02,2.0,Friday

## Example 3: Customer called during closed hours

#### This can get lumped in with intentionally abandoned calls since the customer called and left on their own.

Row 24: Customer left during closed hours, but also during a staff voicemail transfer? 
Why are there three rows for the transfer and 48 seconds of time when the transfer recording is only 5 seconds long?

In [94]:
calls_customer_left[calls_customer_left["Call ID"] == 3]

,Call ID,Contact Session ID,EP Name,Flow Name,Activity Name,Queue Name,Termination Reason,Activity Start Timestamp,Time Difference,weekday
11,3,1b35074f-6d8b-4132-99a2-32ae83ea54cf,Main Number Telephony EP,NaN,NaN,NaN,NaN,2025-03-16 02:39:46,NaN,Sunday
12,3,1b35074f-6d8b-4132-99a2-32ae83ea54cf,NaN,LACMain,NaN,NaN,NaN,2025-03-16 02:39:46,0.0,Sunday
13,3,1b35074f-6d8b-4132-99a2-32ae83ea54cf,Main Number Telephony EP,NaN,LanguageSelectionMenu,NaN,NaN,2025-03-16 02:39:46,0.0,Sunday
14,3,1b35074f-6d8b-4132-99a2-32ae83ea54cf,Main Number Telephony EP,LACMain,NaN,NaN,NaN,2025-03-16 02:39:46,0.0,Sunday
15,3,1b35074f-6d8b-4132-99a2-32ae83ea54cf,NaN,ClosedHoursHolidaysMenu,NaN,NaN,NaN,2025-03-16 02:39:56,10.0,Sunday
16,3,1b35074f-6d8b-4132-99a2-32ae83ea54cf,Closed Hours-Holidays Menu Telephony EP,NaN,ClosedMenu,NaN,NaN,2025-03-16 02:39:56,0.0,Sunday
17,3,1b35074f-6d8b-4132-99a2-32ae83ea54cf,Closed Hours-Holidays Menu Telephony EP,NaN,AddressFaxHoursMenu,NaN,NaN,2025-03-16 02:40:48,52.0,Sunday
18,3,1b35074f-6d8b-4132-99a2-32ae83ea54cf,Closed Hours-Holidays Menu Telephony EP,NaN,ClosedMenu,NaN,NaN,2025-03-16 02:41:21,33.0,Sunday
19,3,1b35074f-6d8b-4132-99a2-32ae83ea54cf,Closed Hours-Holidays Menu Telephony EP,NaN,StaffDirectoryEnglishTransfer,NaN,NaN,2025-03-16 02:41:30,9.0,Sunday
20,3,1b35074f-6d8b-4132-99a2-32ae83ea54cf,NaN,NaN,NaN,Staff Directory English Transfer,NaN,2025-03-16 02:41:30,0.0,Sunday
21,3,1b35074f-6d8b-4132-99a2-32ae83ea54cf,Closed Hours-Holidays Menu Telephony EP,NaN,NaN,NaN,NaN,2025-03-16 02:41:30,0.0,Sunday
22,3,1b35074f-6d8b-4132-99a2-32ae83ea54cf,Closed Hours-Holidays Menu Telephony EP,NaN,NaN,Staff Directory English Transfer,NaN,2025-03-16 02:41:30,0.0,Sunday
23,3,1b35074f-6d8b-4132-99a2-32ae83ea54cf,Closed Hours-Holidays Menu Telephony EP,NaN,NaN,Staff Directory English Transfer,NaN,2025-03-16 02:41:30,0.0,Sunday
24,3,1b35074f-6d8b-4132-99a2-32ae83ea54cf,Closed Hours-Holidays Menu Telephony EP,NaN,NaN,Staff Directory English Transfer,Customer Left,2025-03-16 02:42:18,48.0,Sunday

#### Seems like this person moved through all the menus and left. No voicemails

In [96]:
calls_customer_left[calls_customer_left["Call ID"] == 25]

,Call ID,Contact Session ID,EP Name,Flow Name,Activity Name,Queue Name,Termination Reason,Activity Start Timestamp,Time Difference,weekday
224,25,0d7b7955-b2d1-4383-ba0d-847648020b54,Main Number Telephony EP,NaN,NaN,NaN,NaN,2025-03-16 20:35:14,NaN,Sunday
225,25,0d7b7955-b2d1-4383-ba0d-847648020b54,NaN,LACMain,NaN,NaN,NaN,2025-03-16 20:35:14,0.0,Sunday
226,25,0d7b7955-b2d1-4383-ba0d-847648020b54,Main Number Telephony EP,NaN,LanguageSelectionMenu,NaN,NaN,2025-03-16 20:35:14,0.0,Sunday
227,25,0d7b7955-b2d1-4383-ba0d-847648020b54,Main Number Telephony EP,LACMain,NaN,NaN,NaN,2025-03-16 20:35:14,0.0,Sunday
228,25,0d7b7955-b2d1-4383-ba0d-847648020b54,NaN,ClosedHoursHolidaysMenu,NaN,NaN,NaN,2025-03-16 20:35:26,12.0,Sunday
229,25,0d7b7955-b2d1-4383-ba0d-847648020b54,Closed Hours-Holidays Menu Telephony EP,NaN,ClosedMenu,NaN,NaN,2025-03-16 20:35:26,0.0,Sunday
230,25,0d7b7955-b2d1-4383-ba0d-847648020b54,Closed Hours-Holidays Menu Telephony EP,NaN,AddressFaxHoursMenu,NaN,NaN,2025-03-16 20:36:13,47.0,Sunday
231,25,0d7b7955-b2d1-4383-ba0d-847648020b54,Closed Hours-Holidays Menu Telephony EP,NaN,ClosedMenu,NaN,NaN,2025-03-16 20:36:46,33.0,Sunday
232,25,0d7b7955-b2d1-4383-ba0d-847648020b54,Closed Hours-Holidays Menu Telephony EP,NaN,AddressFaxHoursMenu,NaN,NaN,2025-03-16 20:37:37,51.0,Sunday
233,25,0d7b7955-b2d1-4383-ba0d-847648020b54,Closed Hours-Holidays Menu Telephony EP,NaN,ClosedMenu,NaN,NaN,2025-03-16 20:37:51,14.0,Sunday
234,25,0d7b7955-b2d1-4383-ba0d-847648020b54,Closed Hours-Holidays Menu Telephony EP,NaN,NaN,NaN,Customer Left,2025-03-16 20:37:51,0.0,Sunday

## Example 4: Customer left while hearing something play

#### Did these customers leave during the music played or did they enter a new queue and leave that?

In [109]:
calls_customer_left[calls_customer_left["Call ID"] == 37]

,Call ID,Contact Session ID,EP Name,Flow Name,Activity Name,Queue Name,Termination Reason,Activity Start Timestamp,Time Difference,weekday
363,37,25390a18-15db-4e03-b5f2-bdc52d856154,Main Number Telephony EP,NaN,NaN,NaN,NaN,2025-03-17 07:59:51,NaN,Monday
364,37,25390a18-15db-4e03-b5f2-bdc52d856154,NaN,LACMain,NaN,NaN,NaN,2025-03-17 07:59:51,0.0,Monday
365,37,25390a18-15db-4e03-b5f2-bdc52d856154,Main Number Telephony EP,NaN,LanguageSelectionMenu,NaN,NaN,2025-03-17 07:59:51,0.0,Monday
366,37,25390a18-15db-4e03-b5f2-bdc52d856154,Main Number Telephony EP,LACMain,NaN,NaN,NaN,2025-03-17 07:59:51,0.0,Monday
368,37,25390a18-15db-4e03-b5f2-bdc52d856154,Main Number Telephony EP,NaN,MainMenu,NaN,NaN,2025-03-17 08:00:02,11.0,Monday
376,37,25390a18-15db-4e03-b5f2-bdc52d856154,NaN,PreLegalMenuSeniorsMenu,NaN,NaN,NaN,2025-03-17 08:00:24,22.0,Monday
377,37,25390a18-15db-4e03-b5f2-bdc52d856154,Pre-Legal Menu Seniors Menu Telephony EP,NaN,SeniorsMenu,NaN,NaN,2025-03-17 08:00:24,0.0,Monday
379,37,25390a18-15db-4e03-b5f2-bdc52d856154,Pre-Legal Menu Seniors Menu Telephony EP,NaN,SeniorsConfirmationMenu,NaN,NaN,2025-03-17 08:00:29,5.0,Monday
394,37,25390a18-15db-4e03-b5f2-bdc52d856154,Pre-Legal Menu Seniors Menu Telephony EP,NaN,SuburbsOrCityMenu,NaN,NaN,2025-03-17 08:00:46,17.0,Monday
404,37,25390a18-15db-4e03-b5f2-bdc52d856154,Pre-Legal Menu Seniors Menu Telephony EP,NaN,SeniorsADAPTMenu,NaN,NaN,2025-03-17 08:01:05,19.0,Monday
417,37,25390a18-15db-4e03-b5f2-bdc52d856154,NaN,LegalMenu,NaN,NaN,NaN,2025-03-17 08:01:28,23.0,Monday
418,37,25390a18-15db-4e03-b5f2-bdc52d856154,Legal Menu Telephony EP,NaN,LegalMenu1,NaN,NaN,2025-03-17 08:01:28,0.0,Monday
443,37,25390a18-15db-4e03-b5f2-bdc52d856154,Legal Menu Telephony EP,NaN,LegalMenu2,NaN,NaN,2025-03-17 08:02:04,36.0,Monday
487,37,25390a18-15db-4e03-b5f2-bdc52d856154,NaN,Queues,NaN,NaN,NaN,2025-03-17 08:03:22,78.0,Monday
488,37,25390a18-15db-4e03-b5f2-bdc52d856154,All LAC Queues Telephony EP,NaN,GetLoggedInConsumerAgents,NaN,NaN,2025-03-17 08:03:22,0.0,Monday
489,37,25390a18-15db-4e03-b5f2-bdc52d856154,All LAC Queues Telephony EP,NaN,IntakePreQueueMessage1,NaN,NaN,2025-03-17 08:03:22,0.0,Monday
521,37,25390a18-15db-4e03-b5f2-bdc52d856154,All LAC Queues Telephony EP,NaN,ConsumerQueue,NaN,NaN,2025-03-17 08:04:19,57.0,Monday
522,37,25390a18-15db-4e03-b5f2-bdc52d856154,NaN,NaN,NaN,Consumer,NaN,2025-03-17 08:04:19,0.0,Monday
523,37,25390a18-15db-4e03-b5f2-bdc52d856154,All LAC Queues Telephony EP,NaN,NaN,NaN,NaN,2025-03-17 08:04:19,0.0,Monday
524,37,25390a18-15db-4e03-b5f2-bdc52d856154,All LAC Queues Telephony EP,NaN,NaN,Consumer,NaN,2025-03-17 08:04:19,0.0,Monday
525,37,25390a18-15db-4e03-b5f2-bdc52d856154,All LAC Queues Telephony EP,NaN,PreQueueMessage2,NaN,NaN,2025-03-17 08:04:19,0.0,Monday
530,37,25390a18-15db-4e03-b5f2-bdc52d856154,All LAC Queues Telephony EP,NaN,PlayMOH300s,NaN,NaN,2025-03-17 08:04:31,12.0,Monday
664,37,25390a18-15db-4e03-b5f2-bdc52d856154,All LAC Queues Telephony EP,NaN,QueueMenu1,NaN,NaN,2025-03-17 08:09:33,302.0,Monday
683,37,25390a18-15db-4e03-b5f2-bdc52d856154,All LAC Queues Telephony EP,NaN,PlayMOH300s,NaN,NaN,2025-03-17 08:09:54,21.0,Monday
857,37,25390a18-15db-4e03-b5f2-bdc52d856154,All LAC Queues Telephony EP,NaN,QueueMenu1,NaN,NaN,2025-03-17 08:14:56,302.0,Monday
860,37,25390a18-15db-4e03-b5f2-bdc52d856154,All LAC Queues Telephony EP,NaN,PlayMOH300s,NaN,NaN,2025-03-17 08:15:17,21.0,Monday
922,37,25390a18-15db-4e03-b5f2-bdc52d856154,All LAC Queues Telephony EP,NaN,QueueMenu1,NaN,NaN,2025-03-17 08:20:19,302.0,Monday
928,37,25390a18-15db-4e03-b5f2-bdc52d856154,All LAC Queues Telephony EP,NaN,PlayMOH300s,NaN,NaN,2025-03-17 08:20:41,22.0,Monday
1006,37,25390a18-15db-4e03-b5f2-bdc52d856154,All LAC Queues Telephony EP,NaN,NaN,Consumer,Customer Left,2025-03-17 08:25:25,284.0,Monday

In [110]:
calls_customer_left[calls_customer_left["Call ID"] == 123]

,Call ID,Contact Session ID,EP Name,Flow Name,Activity Name,Queue Name,Termination Reason,Activity Start Timestamp,Time Difference,weekday
1941,123,439a384b-bd90-4b4d-8f51-846716775863,Main Number Telephony EP,NaN,NaN,NaN,NaN,2025-03-17 09:31:32,NaN,Monday
1942,123,439a384b-bd90-4b4d-8f51-846716775863,NaN,LACMain,NaN,NaN,NaN,2025-03-17 09:31:32,0.0,Monday
1943,123,439a384b-bd90-4b4d-8f51-846716775863,Main Number Telephony EP,NaN,LanguageSelectionMenu,NaN,NaN,2025-03-17 09:31:32,0.0,Monday
1944,123,439a384b-bd90-4b4d-8f51-846716775863,Main Number Telephony EP,LACMain,NaN,NaN,NaN,2025-03-17 09:31:32,0.0,Monday
1948,123,439a384b-bd90-4b4d-8f51-846716775863,Main Number Telephony EP,NaN,MainMenu,NaN,NaN,2025-03-17 09:31:42,10.0,Monday
1958,123,439a384b-bd90-4b4d-8f51-846716775863,NaN,PreLegalMenuSeniorsMenu,NaN,NaN,NaN,2025-03-17 09:32:07,25.0,Monday
1959,123,439a384b-bd90-4b4d-8f51-846716775863,Pre-Legal Menu Seniors Menu Telephony EP,NaN,SeniorsMenu,NaN,NaN,2025-03-17 09:32:07,0.0,Monday
1964,123,439a384b-bd90-4b4d-8f51-846716775863,Pre-Legal Menu Seniors Menu Telephony EP,NaN,SeniorsMenu,NaN,NaN,2025-03-17 09:32:18,11.0,Monday
1965,123,439a384b-bd90-4b4d-8f51-846716775863,Pre-Legal Menu Seniors Menu Telephony EP,NaN,SeniorsConfirmationMenu,NaN,NaN,2025-03-17 09:32:19,1.0,Monday
1972,123,439a384b-bd90-4b4d-8f51-846716775863,Pre-Legal Menu Seniors Menu Telephony EP,NaN,SuburbsOrCityMenu,NaN,NaN,2025-03-17 09:32:36,17.0,Monday
1975,123,439a384b-bd90-4b4d-8f51-846716775863,Pre-Legal Menu Seniors Menu Telephony EP,NaN,SuburbanSeniorsMenu,NaN,NaN,2025-03-17 09:32:50,14.0,Monday
2018,123,439a384b-bd90-4b4d-8f51-846716775863,Pre-Legal Menu Seniors Menu Telephony EP,NaN,SuburbanSeniorsMenu,NaN,NaN,2025-03-17 09:34:33,103.0,Monday
2021,123,439a384b-bd90-4b4d-8f51-846716775863,NaN,Queues,NaN,NaN,NaN,2025-03-17 09:34:45,12.0,Monday
2022,123,439a384b-bd90-4b4d-8f51-846716775863,All LAC Queues Telephony EP,NaN,GetLoggedInSubSeniorBenefitsAgents,NaN,NaN,2025-03-17 09:34:45,0.0,Monday
2023,123,439a384b-bd90-4b4d-8f51-846716775863,All LAC Queues Telephony EP,NaN,SubSeniorPreQueueMessage1_1,NaN,NaN,2025-03-17 09:34:45,0.0,Monday
2034,123,439a384b-bd90-4b4d-8f51-846716775863,All LAC Queues Telephony EP,NaN,SubSeniorBenefitsQueue,NaN,NaN,2025-03-17 09:35:43,58.0,Monday
2035,123,439a384b-bd90-4b4d-8f51-846716775863,NaN,NaN,NaN,SubSenior Benefits,NaN,2025-03-17 09:35:43,0.0,Monday
2036,123,439a384b-bd90-4b4d-8f51-846716775863,All LAC Queues Telephony EP,NaN,NaN,NaN,NaN,2025-03-17 09:35:43,0.0,Monday
2037,123,439a384b-bd90-4b4d-8f51-846716775863,All LAC Queues Telephony EP,NaN,NaN,SubSenior Benefits,NaN,2025-03-17 09:35:43,0.0,Monday
2038,123,439a384b-bd90-4b4d-8f51-846716775863,All LAC Queues Telephony EP,NaN,PreQueueMessage2,NaN,NaN,2025-03-17 09:35:43,0.0,Monday
2041,123,439a384b-bd90-4b4d-8f51-846716775863,All LAC Queues Telephony EP,NaN,PlayMOH300s,NaN,NaN,2025-03-17 09:35:55,12.0,Monday
2102,123,439a384b-bd90-4b4d-8f51-846716775863,All LAC Queues Telephony EP,NaN,QueueMenu1,NaN,NaN,2025-03-17 09:40:55,300.0,Monday
2108,123,439a384b-bd90-4b4d-8f51-846716775863,All LAC Queues Telephony EP,NaN,PlayMOH300s,NaN,NaN,2025-03-17 09:41:02,7.0,Monday
2109,123,439a384b-bd90-4b4d-8f51-846716775863,All LAC Queues Telephony EP,NaN,NaN,SubSenior Benefits,Customer Left,2025-03-17 09:41:02,0.0,Monday