In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('total_call_data.csv')

C:\Users\Owner\AppData\Local\Temp\ipykernel_17852\31442611.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('total_call_data.csv')

In [4]:
df['Activity Name'].value_counts()[20:40]

Activity Name
PreTenantMenu                     15545
DivorceOrParentingMenu            14611
AppointmentMenu                   13576
OtherLegalOtherMenu               13067
HelpWithLegalorOtherReasonMenu    12098
PreQueueMessage2                  11488
LegalServerScreenPop              11369
FarmworkerMainMenu                 9832
ReadANI                            9213
DisconnectContact                  9121
CCB                                8754
PlayCCBConfirmation                8754
SuburbanSeniorsMenu                8642
BenefitsMenu                       7834
FrontDeskTransfer1                 7679
IntakePreQueueMessage1             7094
FrontDeskTransfer2                 6705
ImmigrationMenu                    5156
EmploymentMenu                     5068
SubSeniorPreQueueMessage1_1        4787
Name: count, dtype: int64

In [10]:
# Example target activity names
target_activities = ["PreQueueMessage1", "PreQueueMessage2", "QueueMenu1", "PlayMOH300s"]

# Assuming your DataFrame is named df and has at least these columns:
# "Call ID" (or whatever uniquely identifies a call) and "Activity Name"

# Step 1: Find all call IDs that hit one of the target activities
call_ids_to_keep = df.loc[df["Activity Name"].isin(target_activities), "Contact Session ID"].unique()

# Step 2: Filter to keep *all* rows of those calls
filtered_df = df[df["Contact Session ID"].isin(call_ids_to_keep)].copy().reset_index(drop = True)

In [73]:
menus_df

                         Contact Session ID        Prev Activity
0      02f3875b-ceae-4836-9786-1daf78f2841b           LegalMenu2
1      04617841-2326-4535-bd4c-a9954f1cf4d7  SuburbanSeniorsMenu
2      06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45  SuburbanSeniorsMenu
3      07f88374-f76b-4b0a-819e-0de67976e69a  SuburbanSeniorsMenu
4      093223fc-33fe-48f0-aa19-f65535bfaec8  SuburbanSeniorsMenu
...                                     ...                  ...
11483  c47cebb7-692a-495b-981c-a8ea7c2d2d71      ImmigrationMenu
11484  4b3b63de-f471-42be-a8a0-4ca70d57ea2b           TenantMenu
11485  289669ce-eab1-4a70-9aee-9eb7362642a2         BenefitsMenu
11486  da2bb927-df57-46c7-9a34-0e973c62fd3f         BenefitsMenu
11487  6b3acf29-e8e2-43ac-b434-ab6b5c888da3        PreTenantMenu

[11488 rows x 2 columns]

In [74]:
filtered_df.loc[filtered_df['Contact Session ID'] == '02f3875b-ceae-4836-9786-1daf78f2841b']

,Contact Session ID,EP Name,Flow Name,Activity Name,Activity Start Timestamp,Queue Name,Agent Name,Termination Reason,hour
0,02f3875b-ceae-4836-9786-1daf78f2841b,Main Number Telephony EP,NaN,NaN,2025-01-17 08:01:09,NaN,NaN,NaN,8
1,02f3875b-ceae-4836-9786-1daf78f2841b,NaN,LACMain,NaN,2025-01-17 08:01:09,NaN,NaN,NaN,8
2,02f3875b-ceae-4836-9786-1daf78f2841b,Main Number Telephony EP,NaN,LanguageSelectionMenu,2025-01-17 08:01:09,NaN,NaN,NaN,8
3,02f3875b-ceae-4836-9786-1daf78f2841b,Main Number Telephony EP,LACMain,NaN,2025-01-17 08:01:09,NaN,NaN,NaN,8
4,02f3875b-ceae-4836-9786-1daf78f2841b,Main Number Telephony EP,NaN,MainMenu,2025-01-17 08:01:21,NaN,NaN,NaN,8
5,02f3875b-ceae-4836-9786-1daf78f2841b,NaN,PreLegalMenuSeniorsMenu,NaN,2025-01-17 08:01:45,NaN,NaN,NaN,8
6,02f3875b-ceae-4836-9786-1daf78f2841b,Pre-Legal Menu Seniors Menu Telephony EP,NaN,SeniorsMenu,2025-01-17 08:01:45,NaN,NaN,NaN,8
7,02f3875b-ceae-4836-9786-1daf78f2841b,NaN,LegalMenu,NaN,2025-01-17 08:01:53,NaN,NaN,NaN,8
8,02f3875b-ceae-4836-9786-1daf78f2841b,Legal Menu Telephony EP,NaN,LegalMenu1,2025-01-17 08:01:53,NaN,NaN,NaN,8
9,02f3875b-ceae-4836-9786-1daf78f2841b,Legal Menu Telephony EP,NaN,LegalMenu2,2025-01-17 08:02:29,NaN,NaN,NaN,8
10,02f3875b-ceae-4836-9786-1daf78f2841b,NaN,Queues,NaN,2025-01-17 08:03:48,NaN,NaN,NaN,8
11,02f3875b-ceae-4836-9786-1daf78f2841b,All LAC Queues Telephony EP,NaN,GetLoggedInConsumerAgents,2025-01-17 08:03:48,NaN,NaN,NaN,8
12,02f3875b-ceae-4836-9786-1daf78f2841b,All LAC Queues Telephony EP,NaN,IntakePreQueueMessage1,2025-01-17 08:03:48,NaN,NaN,NaN,8
13,02f3875b-ceae-4836-9786-1daf78f2841b,All LAC Queues Telephony EP,NaN,ConsumerQueue,2025-01-17 08:04:51,NaN,NaN,NaN,8
14,02f3875b-ceae-4836-9786-1daf78f2841b,NaN,NaN,NaN,2025-01-17 08:04:51,Consumer,NaN,NaN,8
15,02f3875b-ceae-4836-9786-1daf78f2841b,All LAC Queues Telephony EP,NaN,NaN,2025-01-17 08:04:51,Consumer,NaN,NaN,8
16,02f3875b-ceae-4836-9786-1daf78f2841b,All LAC Queues Telephony EP,NaN,PreQueueMessage2,2025-01-17 08:04:51,NaN,NaN,NaN,8
17,02f3875b-ceae-4836-9786-1daf78f2841b,All LAC Queues Telephony EP,NaN,PlayMOH300s,2025-01-17 08:05:03,NaN,NaN,NaN,8
18,02f3875b-ceae-4836-9786-1daf78f2841b,All LAC Queues Telephony EP,NaN,QueueMenu1,2025-01-17 08:10:04,NaN,NaN,NaN,8
19,02f3875b-ceae-4836-9786-1daf78f2841b,NaN,CourtesyCallback,NaN,2025-01-17 08:10:20,NaN,NaN,NaN,8
20,02f3875b-ceae-4836-9786-1daf78f2841b,Courtesy Callback Telephony EP,NaN,ReadANI,2025-01-17 08:10:20,NaN,NaN,NaN,8
21,02f3875b-ceae-4836-9786-1daf78f2841b,Courtesy Callback Telephony EP,NaN,CCB,2025-01-17 08:10:35,NaN,NaN,NaN,8
22,02f3875b-ceae-4836-9786-1daf78f2841b,NaN,NaN,NaN,2025-01-17 08:10:35,Consumer,NaN,NaN,8
23,02f3875b-ceae-4836-9786-1daf78f2841b,Courtesy Callback Telephony EP,NaN,PlayCCBConfirmation,2025-01-17 08:10:35,NaN,NaN,NaN,8
24,02f3875b-ceae-4836-9786-1daf78f2841b,Courtesy Callback Telephony EP,NaN,DisconnectContact1,2025-01-17 08:10:50,NaN,NaN,NaN,8
25,02f3875b-ceae-4836-9786-1daf78f2841b,NaN,NaN,NaN,2025-01-18 05:04:51,Consumer,NaN,NaN,5
26,02f3875b-ceae-4836-9786-1daf78f2841b,NaN,NaN,NaN,2025-01-18 05:04:51,Consumer,NaN,NaN,5
27,02f3875b-ceae-4836-9786-1daf78f2841b,Courtesy Callback Telephony EP,NaN,CallbackRetry,2025-01-18 05:05:02,NaN,NaN,NaN,5
28,02f3875b-ceae-4836-9786-1daf78f2841b,NaN,NaN,NaN,2025-01-18 05:05:02,Consumer,NaN,NaN,5
29,02f3875b-ceae-4836-9786-1daf78f2841b,NaN,NaN,NaN,2025-01-18 05:05:02,Consumer,NaN,NaN,5
30,02f3875b-ceae-4836-9786-1daf78f2841b,Courtesy Callback Telephony EP,NaN,NaN,2025-01-18 05:05:02,Consumer,NaN,NaN,5
5112,02f3875b-ceae-4836-9786-1daf78f2841b,NaN,NaN,NaN,2025-01-19 02:05:02,Consumer,NaN,NaN,2
5113,02f3875b-ceae-4836-9786-1daf78f2841b,NaN,NaN,NaN,2025-01-19 02:05:02,Consumer,NaN,NaN,2
5114,02f3875b-ceae-4836-9786-1daf78f2841b,Courtesy Callback Telephony EP,NaN,CallbackRetry,2025-01-19 02:05:12,NaN,NaN,NaN,2
5115,02f3875b-ceae-4836-9786-1daf78f2841b,NaN,NaN,NaN,2025-01-19 02:05:12,Consumer,NaN,NaN,2
5116,02f3875b-ceae-4836-9786-1daf78f2841b,NaN,NaN,NaN,2025-01-19 02:05:12,Consumer,NaN,NaN,2
5117,02f3875b-ceae-4836-9786-1daf78f2841b,Courtesy Callback Telephony EP,NaN,NaN,2025-01-19 02:05:12,Consumer,NaN,NaN,2
5242,02f3875b-ceae-4836-9786-1daf78f2841b,NaN,NaN,NaN,2025-01-19 23:05:12,Consumer,NaN,NaN,23
5243,02f3875b-ceae-4836-9786-1daf78f2841b,NaN,NaN,NaN,2025-01-19 23:05:12,Consumer,NaN,NaN,23
5244,02f3875b-ceae-4836-9786-1daf78f2841b,Courtesy Callback Telephony EP,NaN,CallbackRetry,2025-01-19 23:05:22,NaN,NaN,NaN,23
5245,02f3875b-ceae-4836-9786-1daf78f2841b,NaN,NaN,NaN,2025-01-19 23:05:22,Consumer,NaN,NaN,23
5246,02f3875b-ceae-4836-9786-1daf78f2841b,NaN,NaN,NaN,2025-01-19 23:05:22,Consumer,NaN,NaN,23
5247,02f3875b-ceae-4836-9786-1daf78f2841b,Courtesy Callback Telephony EP,NaN,NaN,2025-01-19 23:05:22,Consumer,NaN,NaN,23
5363,02f3875b-ceae-4836-9786-1daf78f2841b,NaN,NaN,NaN,2025-01-20 20:05:22,Consumer,NaN,NaN,20
5364,02f3875b-ceae-4836-9786-1daf78f2841b,NaN,NaN,NaN,2025-01-20 20:05:22,Consumer,NaN,NaN,20
5365,02f3875b-ceae-4836-9786-1daf78f2841b,Courtesy Callback Telephony EP,NaN,CallbackRetry,2025-01-20 20:05:32,NaN,NaN,NaN,20
5366,02f3875b-ceae-4836-9786-1daf78f2841b,NaN,NaN,NaN,2025-01-20 20:05:32,Consumer,NaN,NaN,20
5367,02f3875b-ceae-4836-9786-1daf78f2841b,NaN,NaN,NaN,2025-01-20 20:05:32,Consumer,NaN,NaN,20
5368,02f3875b-ceae-4836-9786-1daf78f2841b,Courtesy Callback Telephony EP,NaN,NaN,2025-01-20 20:05:32,Consumer,NaN,NaN,20
6184,02f3875b-ceae-4836-9786-1daf78f2841b,NaN,NaN,NaN,2025-01-21 17:05:32,Consumer,NaN,NaN,17
6185,02f3875b-ceae-4836-9786-1daf78f2841b,NaN,NaN,NaN,2025-01-21 17:05:32,Consumer,NaN,NaN,17
6186,02f3875b-ceae-4836-9786-1daf78f2841b,Courtesy Callback Telephony EP,NaN,CallbackRetry,2025-01-21 17:05:42,NaN,NaN,NaN,17
6187,02f3875b-ceae-4836-9786-1daf78f2841b,NaN,NaN,NaN,2025-01-21 17:05:42,Consumer,NaN,NaN,17
6188,02f3875b-ceae-4836-9786-1daf78f2841b,NaN,NaN,NaN,2025-01-21 17:05:42,Consumer,NaN,NaN,17
6189,02f3875b-ceae-4836-9786-1daf78f2841b,Courtesy Callback Telephony EP,NaN,NaN,2025-01-21 17:05:42,Consumer,NaN,NaN,17
7582,02f3875b-ceae-4836-9786-1daf78f2841b,NaN,NaN,NaN,2025-01-22 14:05:42,Consumer,NaN,NaN,14
7583,02f3875b-ceae-4836-9786-1daf78f2841b,NaN,NaN,NaN,2025-01-22 14:05:42,Consumer,NaN,NaN,14
7584,02f3875b-ceae-4836-9786-1daf78f2841b,Courtesy Callback Telephony EP,NaN,DisconnectCallbackContact,2025-01-22 14:05:43,NaN,NaN,NaN,14
7585,02f3875b-ceae-4836-9786-1daf78f2841b,Courtesy Callback Telephony EP,NaN,NaN,2025-01-22 14:05:43,Consumer,NaN,NaN,14

In [28]:
# This code tells use which menus lead to the most queues
results = []

for contact_id in filtered_df['Contact Session ID'].unique():
    temp = filtered_df.loc[filtered_df['Contact Session ID'] == contact_id].copy()
    temp = temp.sort_values('Activity Start Timestamp').reset_index(drop=True)
    
    mask = temp['Activity Name'].str.contains('queue', case=False, na=False) | \
           temp['Flow Name'].str.contains('queue', case=False, na=False)
    
    queue_rows = temp[mask]
    if not queue_rows.empty:
        first_queue_index = queue_rows.index[0]
        if first_queue_index > 0:
            prev_activity = temp.loc[first_queue_index - 1, 'Activity Name']
            results.append({'Contact Session ID': contact_id, 'Prev Activity': prev_activity})

menus_df = pd.DataFrame(results)

In [79]:
# Uses Queue Name
# create queue_name_df similar to menus_df but using 'Queue Name' instead of 'Activity Name'
results = []


for contact_id in filtered_df['Contact Session ID'].unique():
    temp = filtered_df.loc[filtered_df['Contact Session ID'] == contact_id].copy()
    temp = temp.sort_values('Activity Start Timestamp').reset_index(drop=True)
    
    for i in range(1, len(temp)):
        current_row = temp.iloc[i]
        prev_row = temp.iloc[i - 1]
        queue_name = current_row['Queue Name']
        if queue_name not in [np.nan, '']:
            
            results.append({'Contact Session ID': contact_id, 'Queue Name': queue_name})
            break
queue_name_df = pd.DataFrame(results)

In [80]:
queue_name_df['Queue Name'].value_counts()

Queue Name
Family                      1874
Consumer                    1399
SubSenior Other             1158
Housing                     1007
Benefits                     773
SubSenior Benefits           662
SubSenior Tenant             656
SubSenior Consumer           497
Employment                   492
SubSenior Family             462
SubSenior Homeowner          440
ADAPT                        368
SubSenior ADAPT              255
Family SP                    254
Immigration SP               164
SubSenior Employment         143
Consumer SP                  113
Benefits SP                   95
Education                     82
Employment SP                 81
SubSenior Other SP            62
Immigration                   55
SubSenior Consumer SP         44
SubSenior Benefits SP         44
Other SubSeniors              33
ADAPT SP                      28
SubSenior Family SP           27
SubSenior Homeowner SP        22
Housing SP                    21
Benefits SubSeniors           19
Consumer SubSeniors           19
SubSenior Employment SP       17
Homeowner SubSeniors          16
Housing SubSeniors            15
SubSenior Tenant SP           14
Education SP                  14
Family SubSeniors             13
ADAPT SubSeniors              11
Benefits SubSeniors SP         9
Other SubSeniors SP            7
SubSenior ADAPT SP             7
Employment SubSeniors          5
Family SubSeniors SP           3
Consumer SubSeniors SP         3
Housing SubSeniors SP          2
ADAPT SubSeniors SP            2
Employment SubSeniors SP       1
Name: count, dtype: int64

In [ ]:
# Uses Activity Name

results = []

for contact_id in filtered_df['Contact Session ID'].unique():
    temp = filtered_df.loc[filtered_df['Contact Session ID'] == contact_id].copy()
    temp = temp.sort_values('Activity Start Timestamp').reset_index(drop=True)
    
    mask = temp['Activity Name'].str.contains('queue', case=False, na=False) | \
           temp['Flow Name'].str.contains('queue', case=False, na=False)
    
    queue_rows = temp[mask]
    if not queue_rows.empty:
        first_queue_index = queue_rows.index[0]
        
        # Walk backward to find the most recent non-Na activity not starting with GetLoggedIn
        prev_activity = None
        for i in range(first_queue_index - 1, -1, -1):  # iterate backward
            activity = temp.loc[i, 'Activity Name']
            if pd.notna(activity) and not str(activity).startswith('GetLoggedIn'):
                prev_activity = activity
                break
        
        # Only record if we actually found a valid previous activity
        if prev_activity:
            results.append({
                'Contact Session ID': contact_id,
                'Prev Activity': prev_activity
            })

menus_df = pd.DataFrame(results)

In [68]:
# Here we see that SuburbanSeniorsMenu has almost 3 times as many queue leads as the next highest
# However, this could be skewed if some menus are named differently or are not correclty grouped together
menus_df['Prev Activity'].value_counts()

Prev Activity
SuburbanSeniorsMenu       3973
FamilyMenu                1362
LegalMenu2                1089
TenantMenu                1028
BenefitsMenu               868
DivorceOrParentingMenu     776
PreTenantMenu              687
HousingMenu                594
EmploymentMenu             573
SeniorsADAPTMenu           221
ImmigrationMenu            219
SimpleDivorceMenu           86
SuburbsOrCityMenu            8
OtherLegalMenu               2
LegalMenu1                   1
TenantDeterrenceMenu         1
Name: count, dtype: int64

In [ ]:
queue_times = {}

results = []

for contact_id in filtered_df['Contact Session ID'].unique():
    temp = filtered_df.loc[filtered_df['Contact Session ID'] == contact_id].copy()
    temp = temp.sort_values('Activity Start Timestamp').reset_index(drop=True)
    
    mask = temp['Activity Name'].str.contains('queue', case=False, na=False) | \
           temp['Flow Name'].str.contains('queue', case=False, na=False)
    
    queue_rows = temp[mask]
    if not queue_rows.empty:
        first_queue_index = queue_rows.index[0]
        
        # Walk backward to find the most recent non-Na activity not starting with GetLoggedIn
        prev_activity = None
        for i in range(first_queue_index - 1, -1, -1):  # iterate backward
            activity = temp.loc[i, 'Activity Name']
            if pd.notna(activity) and not str(activity).startswith('GetLoggedIn'):
                prev_activity = activity
                break
        
        # start recording time in queue when we hit PlayMOH300s
        # Record every instance of PlayMOH300s and QueueMenu1 until we exit the queue
        occurences = 0
        for i in range(first_queue_index, len(temp)):
            activity = temp.loc[i, 'Activity Name']
            if activity == 'PlayMOH300s' or activity == 'QueueMenu1':
                occurences += 1
                
                
                # Accumulate time for this previous activity
                if prev_activity not in queue_times:
                    queue_times[prev_activity] = 0
                queue_times[prev_activity] += occurences
            else:
                # Exit the queue when we hit an activity that is not part of the queue flow
                break
for key, value in queue_times.items():
       total = queue_name_df['Queue Name'].value_counts().get(key, 1)

['LegalMenu2',
 'SuburbanSeniorsMenu',
 'DivorceOrParentingMenu',
 'FamilyMenu',
 'HousingMenu',
 'BenefitsMenu',
 'SeniorsADAPTMenu',
 'PreTenantMenu',
 'EmploymentMenu',
 'TenantMenu',
 'ImmigrationMenu',
 'SimpleDivorceMenu',
 'SuburbsOrCityMenu',
 'LegalMenu1',
 'OtherLegalMenu',
 'TenantDeterrenceMenu']

In [71]:
menus_df['Prev Activity'].value_counts().get('LegalMenu2', 1)

np.int64(1089)

In [62]:
filtered_df.loc[filtered_df['Contact Session ID'] == 'c47cebb7-692a-495b-981c-a8ea7c2d2d71']

,Contact Session ID,EP Name,Flow Name,Activity Name,Activity Start Timestamp,Queue Name,Agent Name,Termination Reason,hour
408105,c47cebb7-692a-495b-981c-a8ea7c2d2d71,Main Number Telephony EP,NaN,NaN,2025-03-28 08:08:15,NaN,NaN,NaN,8
408106,c47cebb7-692a-495b-981c-a8ea7c2d2d71,NaN,LACMain,NaN,2025-03-28 08:08:15,NaN,NaN,NaN,8
408107,c47cebb7-692a-495b-981c-a8ea7c2d2d71,Main Number Telephony EP,NaN,LanguageSelectionMenu,2025-03-28 08:08:15,NaN,NaN,NaN,8
408108,c47cebb7-692a-495b-981c-a8ea7c2d2d71,Main Number Telephony EP,LACMain,NaN,2025-03-28 08:08:15,NaN,NaN,NaN,8
408111,c47cebb7-692a-495b-981c-a8ea7c2d2d71,Main Number Telephony EP,NaN,MainMenu,2025-03-28 08:08:23,NaN,NaN,NaN,8
408124,c47cebb7-692a-495b-981c-a8ea7c2d2d71,NaN,PreLegalMenuSeniorsMenu,NaN,2025-03-28 08:08:53,NaN,NaN,NaN,8
408125,c47cebb7-692a-495b-981c-a8ea7c2d2d71,Pre-Legal Menu Seniors Menu Telephony EP,NaN,SeniorsMenu,2025-03-28 08:08:53,NaN,NaN,NaN,8
408138,c47cebb7-692a-495b-981c-a8ea7c2d2d71,Pre-Legal Menu Seniors Menu Telephony EP,NaN,SeniorsMenu,2025-03-28 08:09:06,NaN,NaN,NaN,8
408141,c47cebb7-692a-495b-981c-a8ea7c2d2d71,NaN,LegalMenu,NaN,2025-03-28 08:09:09,NaN,NaN,NaN,8
408142,c47cebb7-692a-495b-981c-a8ea7c2d2d71,Legal Menu Telephony EP,NaN,LegalMenu1,2025-03-28 08:09:09,NaN,NaN,NaN,8
408171,c47cebb7-692a-495b-981c-a8ea7c2d2d71,Legal Menu Telephony EP,NaN,LegalMenu2,2025-03-28 08:09:58,NaN,NaN,NaN,8
408243,c47cebb7-692a-495b-981c-a8ea7c2d2d71,NaN,LegalImmigrationMenu,NaN,2025-03-28 08:12:00,NaN,NaN,NaN,8
408244,c47cebb7-692a-495b-981c-a8ea7c2d2d71,Legal Immigration Menu Telephony EP,NaN,ImmigrationMenu,2025-03-28 08:12:00,NaN,NaN,NaN,8
408247,c47cebb7-692a-495b-981c-a8ea7c2d2d71,NaN,Queues,NaN,2025-03-28 08:12:41,NaN,NaN,NaN,8
408248,c47cebb7-692a-495b-981c-a8ea7c2d2d71,All LAC Queues Telephony EP,NaN,GetLoggedInImmigrationSPAgents,2025-03-28 08:12:41,NaN,NaN,NaN,8
408249,c47cebb7-692a-495b-981c-a8ea7c2d2d71,All LAC Queues Telephony EP,NaN,IntakePreQueueMessage1,2025-03-28 08:12:41,NaN,NaN,NaN,8
408259,c47cebb7-692a-495b-981c-a8ea7c2d2d71,All LAC Queues Telephony EP,NaN,ImmigrationSPQueue,2025-03-28 08:13:55,NaN,NaN,NaN,8
408260,c47cebb7-692a-495b-981c-a8ea7c2d2d71,NaN,NaN,NaN,2025-03-28 08:13:55,Immigration SP,NaN,NaN,8
408261,c47cebb7-692a-495b-981c-a8ea7c2d2d71,All LAC Queues Telephony EP,NaN,NaN,2025-03-28 08:13:55,NaN,NaN,NaN,8
408262,c47cebb7-692a-495b-981c-a8ea7c2d2d71,All LAC Queues Telephony EP,NaN,NaN,2025-03-28 08:13:55,Immigration SP,NaN,NaN,8
408263,c47cebb7-692a-495b-981c-a8ea7c2d2d71,All LAC Queues Telephony EP,NaN,PreQueueMessage2,2025-03-28 08:13:56,NaN,NaN,NaN,8
408265,c47cebb7-692a-495b-981c-a8ea7c2d2d71,All LAC Queues Telephony EP,NaN,PlayMOH300s,2025-03-28 08:14:10,NaN,NaN,NaN,8
408334,c47cebb7-692a-495b-981c-a8ea7c2d2d71,All LAC Queues Telephony EP,NaN,QueueMenu1,2025-03-28 08:19:10,NaN,NaN,NaN,8
408335,c47cebb7-692a-495b-981c-a8ea7c2d2d71,All LAC Queues Telephony EP,NaN,PlayMOH300s,2025-03-28 08:19:41,NaN,NaN,NaN,8
408353,c47cebb7-692a-495b-981c-a8ea7c2d2d71,All LAC Queues Telephony EP,NaN,QueueMenu1,2025-03-28 08:24:41,NaN,NaN,NaN,8
408354,c47cebb7-692a-495b-981c-a8ea7c2d2d71,All LAC Queues Telephony EP,NaN,PlayMOH300s,2025-03-28 08:25:12,NaN,NaN,NaN,8
408368,c47cebb7-692a-495b-981c-a8ea7c2d2d71,All LAC Queues Telephony EP,NaN,QueueMenu1,2025-03-28 08:30:13,NaN,NaN,NaN,8
408369,c47cebb7-692a-495b-981c-a8ea7c2d2d71,All LAC Queues Telephony EP,NaN,PlayMOH300s,2025-03-28 08:30:43,NaN,NaN,NaN,8
408372,c47cebb7-692a-495b-981c-a8ea7c2d2d71,All LAC Queues Telephony EP,NaN,QueueMenu1,2025-03-28 08:35:44,NaN,NaN,NaN,8
408373,c47cebb7-692a-495b-981c-a8ea7c2d2d71,NaN,CourtesyCallback,NaN,2025-03-28 08:36:05,NaN,NaN,NaN,8
408374,c47cebb7-692a-495b-981c-a8ea7c2d2d71,Courtesy Callback Telephony EP,NaN,ReadANI,2025-03-28 08:36:05,NaN,NaN,NaN,8
408375,c47cebb7-692a-495b-981c-a8ea7c2d2d71,Courtesy Callback Telephony EP,NaN,CCB,2025-03-28 08:36:19,NaN,NaN,NaN,8
408376,c47cebb7-692a-495b-981c-a8ea7c2d2d71,NaN,NaN,NaN,2025-03-28 08:36:19,Immigration SP,NaN,NaN,8
408377,c47cebb7-692a-495b-981c-a8ea7c2d2d71,Courtesy Callback Telephony EP,NaN,PlayCCBConfirmation,2025-03-28 08:36:20,NaN,NaN,NaN,8
408378,c47cebb7-692a-495b-981c-a8ea7c2d2d71,Courtesy Callback Telephony EP,NaN,DisconnectContact1,2025-03-28 08:36:31,NaN,NaN,NaN,8
408475,c47cebb7-692a-495b-981c-a8ea7c2d2d71,Courtesy Callback Telephony EP,NaN,NaN,2025-03-28 10:20:27,Immigration SP,Ana Reynoso,Customer Left,10
408476,c47cebb7-692a-495b-981c-a8ea7c2d2d71,Courtesy Callback Telephony EP,NaN,LegalServerScreenPop,2025-03-28 10:20:28,NaN,NaN,NaN,10
408477,c47cebb7-692a-495b-981c-a8ea7c2d2d71,Courtesy Callback Telephony EP,NaN,NaN,2025-03-28 10:20:36,Immigration SP,Ana Reynoso,Customer Left,10
408478,c47cebb7-692a-495b-981c-a8ea7c2d2d71,Courtesy Callback Telephony EP,NaN,NaN,2025-03-28 10:24:09,Immigration SP,Ana Reynoso,Agent Left,10
408479,c47cebb7-692a-495b-981c-a8ea7c2d2d71,NaN,NaN,NaN,2025-03-28 10:24:09,Immigration SP,Ana Reynoso,NaN,10
408480,c47cebb7-692a-495b-981c-a8ea7c2d2d71,NaN,NaN,NaN,2025-03-28 10:24:13,Immigration SP,Ana Reynoso,NaN,10

In [13]:
temp = df.loc[(df['Activity Name'] == 'QueueMenu1') | (df['Activity Name'] == 'PlayMOH300s')].reset_index()

In [18]:
record = 0
for i, row in temp.iterrows():
    if i == 0:
        continue
    if row['Activity Name'] == 'PlayMOH300s':
        if temp.loc[i-1, 'Activity Name'] != 'QueueMenu1':
            print(temp.loc[i-1, 'Activity Name'])
            record += 1
            print(i)

PlayMOH300s
7
PlayMOH300s
8
PlayMOH300s
53
PlayMOH300s
54
PlayMOH300s
111
PlayMOH300s
114
PlayMOH300s
131
PlayMOH300s
282
PlayMOH300s
333
PlayMOH300s
340
PlayMOH300s
359
PlayMOH300s
374
PlayMOH300s
427
PlayMOH300s
464
PlayMOH300s
635
PlayMOH300s
636
PlayMOH300s
637
PlayMOH300s
638
PlayMOH300s
661
PlayMOH300s
687
PlayMOH300s
692
PlayMOH300s
693
PlayMOH300s
700
PlayMOH300s
739
PlayMOH300s
794
PlayMOH300s
820
PlayMOH300s
824
PlayMOH300s
900
PlayMOH300s
901
PlayMOH300s
902
PlayMOH300s
903
PlayMOH300s
904
PlayMOH300s
905
PlayMOH300s
906
PlayMOH300s
907
PlayMOH300s
910
PlayMOH300s
911
PlayMOH300s
912
PlayMOH300s
923
PlayMOH300s
930
PlayMOH300s
941
PlayMOH300s
949
PlayMOH300s
957
PlayMOH300s
965
PlayMOH300s
972
PlayMOH300s
978
PlayMOH300s
984
PlayMOH300s
990
PlayMOH300s
1012
PlayMOH300s
1018
PlayMOH300s
1025
PlayMOH300s
1031
PlayMOH300s
1045
PlayMOH300s
1057
PlayMOH300s
1068
PlayMOH300s
1086
PlayMOH300s
1091
PlayMOH300s
1122
PlayMOH300s
1128
PlayMOH300s
1129
PlayMOH300s
1135
PlayMOH300s
1138
PlayMOH300s
1176
PlayMOH300s
1194
PlayMOH300s
1206
PlayMOH300s
1216
PlayMOH300s
1272
PlayMOH300s
1273
PlayMOH300s
1274
PlayMOH300s
1275
PlayMOH300s
1276
PlayMOH300s
1277
PlayMOH300s
1375
PlayMOH300s
1415
PlayMOH300s
1421
PlayMOH300s
1447
PlayMOH300s
1453
PlayMOH300s
1508
PlayMOH300s
1598
PlayMOH300s
1599
PlayMOH300s
1600
PlayMOH300s
1648
PlayMOH300s
1649
PlayMOH300s
1650
PlayMOH300s
1651
PlayMOH300s
1655
PlayMOH300s
1664
PlayMOH300s
1667
PlayMOH300s
1675
PlayMOH300s
1684
PlayMOH300s
1685
PlayMOH300s
1698
PlayMOH300s
1701
PlayMOH300s
1706
PlayMOH300s
1725
PlayMOH300s
1740
PlayMOH300s
1760
PlayMOH300s
1766
PlayMOH300s
1767
PlayMOH300s
1778
PlayMOH300s
1779
PlayMOH300s
1780
PlayMOH300s
1781
PlayMOH300s
1782
PlayMOH300s
1783
PlayMOH300s
1784
PlayMOH300s
1785
PlayMOH300s
1786
PlayMOH300s
1800
PlayMOH300s
1803
PlayMOH300s
1809
PlayMOH300s
1835
PlayMOH300s
1842
PlayMOH300s
1895
PlayMOH300s
1907
PlayMOH300s
1913
PlayMOH300s
1923
PlayMOH300s
1927
PlayMOH300s
1939
PlayMOH300s
1965
PlayMOH300s
1979
PlayMOH300s
1982
PlayMOH300s
2018
PlayMOH300s
2031
PlayMOH300s
2043
PlayMOH300s
2061
PlayMOH300s
2062
PlayMOH300s
2063
PlayMOH300s
2064
PlayMOH300s
2065
PlayMOH300s
2066
PlayMOH300s
2067
PlayMOH300s
2121
PlayMOH300s
2129
PlayMOH300s
2146
PlayMOH300s
2147
PlayMOH300s
2148
PlayMOH300s
2149
PlayMOH300s
2150
PlayMOH300s
2151
PlayMOH300s
2152
PlayMOH300s
2153
PlayMOH300s
2160
PlayMOH300s
2166
PlayMOH300s
2171
PlayMOH300s
2179
PlayMOH300s
2187
PlayMOH300s
2195
PlayMOH300s
2203
PlayMOH300s
2211
PlayMOH300s
2212
PlayMOH300s
2220
PlayMOH300s
2226
PlayMOH300s
2230
PlayMOH300s
2239
PlayMOH300s
2276
PlayMOH300s
2282
PlayMOH300s
2311
PlayMOH300s
2316
PlayMOH300s
2336
PlayMOH300s
2344
PlayMOH300s
2364
PlayMOH300s
2373
PlayMOH300s
2452
PlayMOH300s
2459
PlayMOH300s
2460
PlayMOH300s
2461
PlayMOH300s
2462
PlayMOH300s
2469
PlayMOH300s
2495
PlayMOH300s
2505
PlayMOH300s
2545
PlayMOH300s
2546
PlayMOH300s
2555
PlayMOH300s
2559
PlayMOH300s
2560
PlayMOH300s
2561
PlayMOH300s
2562
PlayMOH300s
2563
PlayMOH300s
2564
PlayMOH300s
2565
PlayMOH300s
2571
PlayMOH300s
2574
PlayMOH300s
2591
PlayMOH300s
2614
PlayMOH300s
2622
PlayMOH300s
2632
PlayMOH300s
2643
PlayMOH300s
2651
PlayMOH300s
2659
PlayMOH300s
2660
PlayMOH300s
2661
PlayMOH300s
2662
PlayMOH300s
2663
PlayMOH300s
2668
PlayMOH300s
2673
PlayMOH300s
2674
PlayMOH300s
2680
PlayMOH300s
2688
PlayMOH300s
2759
PlayMOH300s
2777
PlayMOH300s
2869
PlayMOH300s
2875
PlayMOH300s
2881
PlayMOH300s
2887
PlayMOH300s
2893
PlayMOH300s
2899
PlayMOH300s
2905
PlayMOH300s
2911
PlayMOH300s
2917
PlayMOH300s
2923
PlayMOH300s
2924
PlayMOH300s
2930
PlayMOH300s
2937
PlayMOH300s
2943
PlayMOH300s
2949
PlayMOH300s
2955
PlayMOH300s
2961
PlayMOH300s
2967
PlayMOH300s
2972
PlayMOH300s
2976
PlayMOH300s
2980
PlayMOH300s
2984
PlayMOH300s
2988
PlayMOH300s
2989
PlayMOH300s
2993
PlayMOH300s
2998
PlayMOH300s
3002
PlayMOH300s
3006
PlayMOH300s
3007
PlayMOH300s
3011
PlayMOH300s
3017
PlayMOH300s
3022
PlayMOH300s
3026
PlayMOH300s
3027
PlayMOH300s
3032
PlayMOH300s
3036
PlayMOH300s
3040
PlayMOH300s
3044
PlayMOH300s
3048
PlayMOH300s
3052
PlayMOH300s
3056
PlayMOH300s
3060
PlayMOH300s
3064
PlayMOH300s
3068
PlayMOH300s
3072
PlayMOH300s
3076
PlayMOH300s
3080
PlayMOH300s
3084
PlayMOH300s
3123
PlayMOH300s
3124
PlayMOH300s
3125
PlayMOH300s
3126
PlayMOH300s
3127
PlayMOH300s
3128
PlayMOH300s
3129
PlayMOH300s
3130
PlayMOH300s
3135
PlayMOH300s
3145
PlayMOH300s
3158
PlayMOH300s
3164
PlayMOH300s
3182
PlayMOH300s
3196
PlayMOH300s
3200
PlayMOH300s
3219
PlayMOH300s
3226
PlayMOH300s
3236
PlayMOH300s
3241
PlayMOH300s
3245
PlayMOH300s
3261
PlayMOH300s
3287
PlayMOH300s
3288
PlayMOH300s
3306
PlayMOH300s
3307
PlayMOH300s
3313
PlayMOH300s
3326
PlayMOH300s
3331
PlayMOH300s
3332
PlayMOH300s
3357
PlayMOH300s
3360
PlayMOH300s
3361
PlayMOH300s
3382
PlayMOH300s
3399
PlayMOH300s
3400
PlayMOH300s
3403
PlayMOH300s
3404
PlayMOH300s
3405
PlayMOH300s
3415
PlayMOH300s
3441
PlayMOH300s
3446
PlayMOH300s
3450
PlayMOH300s
3474
PlayMOH300s
3478
PlayMOH300s
3492
PlayMOH300s
3493
PlayMOH300s
3498
PlayMOH300s
3499
PlayMOH300s
3500
PlayMOH300s
3501
PlayMOH300s
3502
PlayMOH300s
3503
PlayMOH300s
3504
PlayMOH300s
3511
PlayMOH300s
3512
PlayMOH300s
3523
PlayMOH300s
3530
PlayMOH300s
3536
PlayMOH300s
3541
PlayMOH300s
3551
PlayMOH300s
3563
PlayMOH300s
3573
PlayMOH300s
3580
PlayMOH300s
3584
PlayMOH300s
3589
PlayMOH300s
3593
PlayMOH300s
3596
PlayMOH300s
3603
PlayMOH300s
3622
PlayMOH300s
3627
PlayMOH300s
3633
PlayMOH300s
3636
PlayMOH300s
3639
PlayMOH300s
3640
PlayMOH300s
3653
PlayMOH300s
3659
PlayMOH300s
3660
PlayMOH300s
3661
PlayMOH300s
3662
PlayMOH300s
3663
PlayMOH300s
3664
PlayMOH300s
3665
PlayMOH300s
3666
PlayMOH300s
3667
PlayMOH300s
3675
PlayMOH300s
3679
PlayMOH300s
3683
PlayMOH300s
3709
PlayMOH300s
3728
PlayMOH300s
3729
PlayMOH300s
3732
PlayMOH300s
3740
PlayMOH300s
3741
PlayMOH300s
3749
PlayMOH300s
3752
PlayMOH300s
3768
PlayMOH300s
3782
PlayMOH300s
3785
PlayMOH300s
3786
PlayMOH300s
3787
PlayMOH300s
3788
PlayMOH300s
3789
PlayMOH300s
3793
PlayMOH300s
3794
PlayMOH300s
3798
PlayMOH300s
3805
PlayMOH300s
3806
PlayMOH300s
3807
PlayMOH300s
3808
PlayMOH300s
3812
PlayMOH300s
3815
PlayMOH300s
3835
PlayMOH300s
3836
PlayMOH300s
3841
PlayMOH300s
3842
PlayMOH300s
3846
PlayMOH300s
3849
PlayMOH300s
3852
PlayMOH300s
3861
PlayMOH300s
3869
PlayMOH300s
3870
PlayMOH300s
3881
PlayMOH300s
3884
PlayMOH300s
3893
PlayMOH300s
3899
PlayMOH300s
3905
PlayMOH300s
3931
PlayMOH300s
3951
PlayMOH300s
3960
PlayMOH300s
3964
PlayMOH300s
3969
PlayMOH300s
3970
PlayMOH300s
3971
PlayMOH300s
3975
PlayMOH300s
3978
PlayMOH300s
3979
PlayMOH300s
3984
PlayMOH300s
3994
PlayMOH300s
3999
PlayMOH300s
4011
PlayMOH300s
4022
PlayMOH300s
4025
PlayMOH300s
4037
PlayMOH300s
4038
PlayMOH300s
4051
PlayMOH300s
4054
PlayMOH300s
4072
PlayMOH300s
4073
PlayMOH300s
4076
PlayMOH300s
4080
PlayMOH300s
4084
PlayMOH300s
4087
PlayMOH300s
4090
PlayMOH300s
4096
PlayMOH300s
4104
PlayMOH300s
4105
PlayMOH300s
4109
PlayMOH300s
4112
PlayMOH300s
4113
PlayMOH300s
4114
PlayMOH300s
4117
PlayMOH300s
4124
PlayMOH300s
4134
PlayMOH300s
4138
PlayMOH300s
4139
PlayMOH300s
4149
PlayMOH300s
4178
PlayMOH300s
4188
PlayMOH300s
4204
PlayMOH300s
4205
PlayMOH300s
4210
PlayMOH300s
4217
PlayMOH300s
4220
PlayMOH300s
4221
PlayMOH300s
4224
PlayMOH300s
4225
PlayMOH300s
4226
PlayMOH300s
4227
PlayMOH300s
4228
PlayMOH300s
4232
PlayMOH300s
4235
PlayMOH300s
4242
PlayMOH300s
4255
PlayMOH300s
4256
PlayMOH300s
4261
PlayMOH300s
4283
PlayMOH300s
4284
PlayMOH300s
4285
PlayMOH300s
4286
PlayMOH300s
4287
PlayMOH300s
4294
PlayMOH300s
4300
PlayMOH300s
4305
PlayMOH300s
4306
PlayMOH300s
4310
PlayMOH300s
4315
PlayMOH300s
4316
PlayMOH300s
4320
PlayMOH300s
4339
PlayMOH300s
4343
PlayMOH300s
4344
PlayMOH300s
4345
PlayMOH300s
4346
PlayMOH300s
4347
PlayMOH300s
4348
PlayMOH300s
4362
PlayMOH300s
4399
PlayMOH300s
4408
PlayMOH300s
4412
PlayMOH300s
4417
PlayMOH300s
4418
PlayMOH300s
4424
PlayMOH300s
4425
PlayMOH300s
4446
PlayMOH300s
4453
PlayMOH300s
4454
PlayMOH300s
4455
PlayMOH300s
4459
PlayMOH300s
4466
PlayMOH300s
4467
PlayMOH300s
4468
PlayMOH300s
4469
PlayMOH300s
4470
PlayMOH300s
4471
PlayMOH300s
4472
PlayMOH300s
4487
PlayMOH300s
4491
PlayMOH300s
4492
PlayMOH300s
4497
PlayMOH300s
4533
PlayMOH300s
4569
PlayMOH300s
4585
PlayMOH300s
4586
PlayMOH300s
4615
PlayMOH300s
4616
PlayMOH300s
4619
PlayMOH300s
4620
PlayMOH300s
4621
PlayMOH300s
4622
PlayMOH300s
4623
PlayMOH300s
4626
PlayMOH300s
4631
PlayMOH300s
4632
PlayMOH300s
4633
PlayMOH300s
4644
PlayMOH300s
4645
PlayMOH300s
4654
PlayMOH300s
4657
PlayMOH300s
4661
PlayMOH300s
4668
PlayMOH300s
4674
PlayMOH300s
4684
PlayMOH300s
4687
PlayMOH300s
4691
PlayMOH300s
4702
PlayMOH300s
4716
PlayMOH300s
4730
PlayMOH300s
4740
PlayMOH300s
4743
PlayMOH300s
4755
PlayMOH300s
4759
PlayMOH300s
4765
PlayMOH300s
4772
PlayMOH300s
4773
PlayMOH300s
4774
PlayMOH300s
4775
PlayMOH300s
4776
PlayMOH300s
4777
PlayMOH300s
4778
PlayMOH300s
4779
PlayMOH300s
4780
PlayMOH300s
4786
PlayMOH300s
4792
PlayMOH300s
4804
PlayMOH300s
4815
PlayMOH300s
4818
PlayMOH300s
4836
PlayMOH300s
4854
PlayMOH300s
4860
PlayMOH300s
4866
PlayMOH300s
4869
PlayMOH300s
4870
PlayMOH300s
4871
PlayMOH300s
4886
PlayMOH300s
4906
PlayMOH300s
4937
PlayMOH300s
4942
PlayMOH300s
4946
PlayMOH300s
4956
PlayMOH300s
4961
PlayMOH300s
4962
PlayMOH300s
4963
PlayMOH300s
4984
PlayMOH300s
4994
PlayMOH300s
4995
PlayMOH300s
4998
PlayMOH300s
5007
PlayMOH300s
5017
PlayMOH300s
5018
PlayMOH300s
5022
PlayMOH300s
5027
PlayMOH300s
5034
PlayMOH300s
5037
PlayMOH300s
5038
PlayMOH300s
5045
PlayMOH300s
5058
PlayMOH300s
5059
PlayMOH300s
5068
PlayMOH300s
5073
PlayMOH300s
5082
PlayMOH300s
5087
PlayMOH300s
5088
PlayMOH300s
5089
PlayMOH300s
5090
PlayMOH300s
5091
PlayMOH300s
5092
PlayMOH300s
5095
PlayMOH300s
5096
PlayMOH300s
5097
PlayMOH300s
5106
PlayMOH300s
5107
PlayMOH300s
5112
PlayMOH300s
5113
PlayMOH300s
5125
PlayMOH300s
5175
PlayMOH300s
5176
PlayMOH300s
5182
PlayMOH300s
5198
PlayMOH300s
5199
PlayMOH300s
5204
PlayMOH300s
5205
PlayMOH300s
5231
PlayMOH300s
5232
PlayMOH300s
5240
PlayMOH300s
5243
PlayMOH300s
5244
PlayMOH300s
5251
PlayMOH300s
5279
PlayMOH300s
5287
PlayMOH300s
5295
PlayMOH300s
5307
PlayMOH300s
5308
PlayMOH300s
5309
PlayMOH300s
5310
PlayMOH300s
5313
PlayMOH300s
5314
PlayMOH300s
5315
PlayMOH300s
5319
PlayMOH300s
5320
PlayMOH300s
5339
PlayMOH300s
5340
PlayMOH300s
5345
PlayMOH300s
5356
PlayMOH300s
5370
PlayMOH300s
5371
PlayMOH300s
5372
PlayMOH300s
5380
PlayMOH300s
5381
PlayMOH300s
5382
PlayMOH300s
5383
PlayMOH300s
5386
PlayMOH300s
5404
PlayMOH300s
5410
PlayMOH300s
5415
PlayMOH300s
5422
PlayMOH300s
5431
PlayMOH300s
5432
PlayMOH300s
5437
PlayMOH300s
5438
PlayMOH300s
5461
PlayMOH300s
5467
PlayMOH300s
5468
PlayMOH300s
5469
PlayMOH300s
5470
PlayMOH300s
5471
PlayMOH300s
5472
PlayMOH300s
5475
PlayMOH300s
5478
PlayMOH300s
5479
PlayMOH300s
5494
PlayMOH300s
5501
PlayMOH300s
5507
PlayMOH300s
5517
PlayMOH300s
5518
PlayMOH300s
5526
PlayMOH300s
5535
PlayMOH300s
5538
PlayMOH300s
5557
PlayMOH300s
5561
PlayMOH300s
5565
PlayMOH300s
5569
PlayMOH300s
5573
PlayMOH300s
5574
PlayMOH300s
5584
PlayMOH300s
5585
PlayMOH300s
5589
PlayMOH300s
5594
PlayMOH300s
5598
PlayMOH300s
5599
PlayMOH300s
5603
PlayMOH300s
5615
PlayMOH300s
5616
PlayMOH300s
5617
PlayMOH300s
5626
PlayMOH300s
5635
PlayMOH300s
5640
PlayMOH300s
5641
PlayMOH300s
5644
PlayMOH300s
5649
PlayMOH300s
5650
PlayMOH300s
5653
PlayMOH300s
5661
PlayMOH300s
5669
PlayMOH300s
5675
PlayMOH300s
5681
PlayMOH300s
5687
PlayMOH300s
5694
PlayMOH300s
5700
PlayMOH300s
5701
PlayMOH300s
5710
PlayMOH300s
5724
PlayMOH300s
5736
PlayMOH300s
5744
PlayMOH300s
5747
PlayMOH300s
5748
PlayMOH300s
5749
PlayMOH300s
5750
PlayMOH300s
5756
PlayMOH300s
5757
PlayMOH300s
5761
PlayMOH300s
5762
PlayMOH300s
5763
PlayMOH300s
5768
PlayMOH300s
5783
PlayMOH300s
5819
PlayMOH300s
5820
PlayMOH300s
5831
PlayMOH300s
5836
PlayMOH300s
5837
PlayMOH300s
5841
PlayMOH300s
5842
PlayMOH300s
5846
PlayMOH300s
5858
PlayMOH300s
5871
PlayMOH300s
5882
PlayMOH300s
5894
PlayMOH300s
5903
PlayMOH300s
5921
PlayMOH300s
5927
PlayMOH300s
5928
PlayMOH300s
5939
PlayMOH300s
5942
PlayMOH300s
5943
PlayMOH300s
5948
PlayMOH300s
5951
PlayMOH300s
5952
PlayMOH300s
5953
PlayMOH300s
5954
PlayMOH300s
5970
PlayMOH300s
5971
PlayMOH300s
5972
PlayMOH300s
5981
PlayMOH300s
5985
PlayMOH300s
5988
PlayMOH300s
5995
PlayMOH300s
5996
PlayMOH300s
6000
PlayMOH300s
6008
PlayMOH300s
6012
PlayMOH300s
6018
PlayMOH300s
6025
PlayMOH300s
6031
PlayMOH300s
6034
PlayMOH300s
6038
PlayMOH300s
6042
PlayMOH300s
6077
PlayMOH300s
6081
PlayMOH300s
6101
PlayMOH300s
6104
PlayMOH300s
6108
PlayMOH300s
6109
PlayMOH300s
6116
PlayMOH300s
6117
PlayMOH300s
6129
PlayMOH300s
6133
PlayMOH300s
6141
PlayMOH300s
6145
PlayMOH300s
6146
PlayMOH300s
6147
PlayMOH300s
6148
PlayMOH300s
6151
PlayMOH300s
6158
PlayMOH300s
6163
PlayMOH300s
6166
PlayMOH300s
6183
PlayMOH300s
6194
PlayMOH300s
6197
PlayMOH300s
6207
PlayMOH300s
6208
PlayMOH300s
6215
PlayMOH300s
6216
PlayMOH300s
6219
PlayMOH300s
6223
PlayMOH300s
6226
PlayMOH300s
6227
PlayMOH300s
6232
PlayMOH300s
6233
PlayMOH300s
6241
PlayMOH300s
6260
PlayMOH300s
6261
PlayMOH300s
6262
PlayMOH300s
6273
PlayMOH300s
6276
PlayMOH300s
6277
PlayMOH300s
6278
PlayMOH300s
6279
PlayMOH300s
6280
PlayMOH300s
6281
PlayMOH300s
6290
PlayMOH300s
6291
PlayMOH300s
6292
PlayMOH300s
6293
PlayMOH300s
6294
PlayMOH300s
6300
PlayMOH300s
6322
PlayMOH300s
6332
PlayMOH300s
6333
PlayMOH300s
6334
PlayMOH300s
6335
PlayMOH300s
6336
PlayMOH300s
6337
PlayMOH300s
6338
PlayMOH300s
6349
PlayMOH300s
6350
PlayMOH300s
6351
PlayMOH300s
6354
PlayMOH300s
6355
PlayMOH300s
6364
PlayMOH300s
6367
PlayMOH300s
6375
PlayMOH300s
6384
PlayMOH300s
6387
PlayMOH300s
6388
PlayMOH300s
6389
PlayMOH300s
6395
PlayMOH300s
6402
PlayMOH300s
6411
PlayMOH300s
6417
PlayMOH300s
6429
PlayMOH300s
6529
PlayMOH300s
6530
PlayMOH300s
6531
PlayMOH300s
6532
PlayMOH300s
6535
PlayMOH300s
6560
PlayMOH300s
6563
PlayMOH300s
6567
PlayMOH300s
6584
PlayMOH300s
6585
PlayMOH300s
6586
PlayMOH300s
6587
PlayMOH300s
6588
PlayMOH300s
6593
PlayMOH300s
6594
PlayMOH300s
6595
PlayMOH300s
6600
PlayMOH300s
6607
PlayMOH300s
6608
PlayMOH300s
6616
PlayMOH300s
6617
PlayMOH300s
6632
PlayMOH300s
6643
PlayMOH300s
6652
PlayMOH300s
6653
PlayMOH300s
6659
PlayMOH300s
6660
PlayMOH300s
6661
PlayMOH300s
6664
PlayMOH300s
6679
PlayMOH300s
6682
PlayMOH300s
6683
PlayMOH300s
6684
PlayMOH300s
6685
PlayMOH300s
6686
PlayMOH300s
6687
PlayMOH300s
6688
PlayMOH300s
6689
PlayMOH300s
6690
PlayMOH300s
6696
PlayMOH300s
6704
PlayMOH300s
6705
PlayMOH300s
6706
PlayMOH300s
6718
PlayMOH300s
6721
PlayMOH300s
6727
PlayMOH300s
6733
PlayMOH300s
6734
PlayMOH300s
6739
PlayMOH300s
6743
PlayMOH300s
6746
PlayMOH300s
6747
PlayMOH300s
6753
PlayMOH300s
6757
PlayMOH300s
6777
PlayMOH300s
6781
PlayMOH300s
6785
PlayMOH300s
6789
PlayMOH300s
6793
PlayMOH300s
6797
PlayMOH300s
6801
PlayMOH300s
6805
PlayMOH300s
6809
PlayMOH300s
6812
PlayMOH300s
6816
PlayMOH300s
6823
PlayMOH300s
6824
PlayMOH300s
6857
PlayMOH300s
6860
PlayMOH300s
6861
PlayMOH300s
6862
PlayMOH300s
6863
PlayMOH300s
6864
PlayMOH300s
6865
PlayMOH300s
6873
PlayMOH300s
6883
PlayMOH300s
6893
PlayMOH300s
6894
PlayMOH300s
6903
PlayMOH300s
6908
PlayMOH300s
6912
PlayMOH300s
6916
PlayMOH300s
6921
PlayMOH300s
6943
PlayMOH300s
6946
PlayMOH300s
6949
PlayMOH300s
6958
PlayMOH300s
6959
PlayMOH300s
6962
PlayMOH300s
6963
PlayMOH300s
6966
PlayMOH300s
6967
PlayMOH300s
6975
PlayMOH300s
6976
PlayMOH300s
6987
PlayMOH300s
6992
PlayMOH300s
7004
PlayMOH300s
7008
PlayMOH300s
7012
PlayMOH300s
7021
PlayMOH300s
7063
PlayMOH300s
7068
PlayMOH300s
7069
PlayMOH300s
7072
PlayMOH300s
7073
PlayMOH300s
7074
PlayMOH300s
7075
PlayMOH300s
7079
PlayMOH300s
7089
PlayMOH300s
7101
PlayMOH300s
7104
PlayMOH300s
7105
PlayMOH300s
7134
PlayMOH300s
7138
PlayMOH300s
7150
PlayMOH300s
7154
PlayMOH300s
7157
PlayMOH300s
7162
PlayMOH300s
7163
PlayMOH300s
7174
PlayMOH300s
7175
PlayMOH300s
7176
PlayMOH300s
7177
PlayMOH300s
7181
PlayMOH300s
7190
PlayMOH300s
7198
PlayMOH300s
7202
PlayMOH300s
7203
PlayMOH300s
7204
PlayMOH300s
7205
PlayMOH300s
7206
PlayMOH300s
7207
PlayMOH300s
7235
PlayMOH300s
7236
PlayMOH300s
7237
PlayMOH300s
7238
PlayMOH300s
7241
PlayMOH300s
7244
PlayMOH300s
7251
PlayMOH300s
7256
PlayMOH300s
7266
PlayMOH300s
7267
PlayMOH300s
7268
PlayMOH300s
7278
PlayMOH300s
7287
PlayMOH300s
7302
PlayMOH300s
7303
PlayMOH300s
7314
PlayMOH300s
7321
PlayMOH300s
7324
PlayMOH300s
7328
PlayMOH300s
7340
PlayMOH300s
7341
PlayMOH300s
7351
PlayMOH300s
7352
PlayMOH300s
7358
PlayMOH300s
7359
PlayMOH300s
7362
PlayMOH300s
7363
PlayMOH300s
7364
PlayMOH300s
7368
PlayMOH300s
7442
PlayMOH300s
7443
PlayMOH300s
7448
PlayMOH300s
7451
PlayMOH300s
7454
PlayMOH300s
7455
PlayMOH300s
7456
PlayMOH300s
7459
PlayMOH300s
7468
PlayMOH300s
7471
PlayMOH300s
7475
PlayMOH300s
7476
PlayMOH300s
7480
PlayMOH300s
7484
PlayMOH300s
7485
PlayMOH300s
7486
PlayMOH300s
7496
PlayMOH300s
7497
PlayMOH300s
7505
PlayMOH300s
7506
PlayMOH300s
7513
PlayMOH300s
7514
PlayMOH300s
7526
PlayMOH300s
7527
PlayMOH300s
7551
PlayMOH300s
7558
PlayMOH300s
7605
PlayMOH300s
7606
PlayMOH300s
7607
PlayMOH300s
7608
PlayMOH300s
7609
PlayMOH300s
7613
PlayMOH300s
7618
PlayMOH300s
7619
PlayMOH300s
7627
PlayMOH300s
7639
PlayMOH300s
7651
PlayMOH300s
7658
PlayMOH300s
7661
PlayMOH300s
7666
PlayMOH300s
7677
PlayMOH300s
7682
PlayMOH300s
7687
PlayMOH300s
7699
PlayMOH300s
7700
PlayMOH300s
7701
PlayMOH300s
7702
PlayMOH300s
7708
PlayMOH300s
7711
PlayMOH300s
7719
PlayMOH300s
7720
PlayMOH300s
7723
PlayMOH300s
7732
PlayMOH300s
7735
PlayMOH300s
7739
PlayMOH300s
7744
PlayMOH300s
7758
PlayMOH300s
7763
PlayMOH300s
7785
PlayMOH300s
7788
PlayMOH300s
7797
PlayMOH300s
7798
PlayMOH300s
7799
PlayMOH300s
7800
PlayMOH300s
7801
PlayMOH300s
7802
PlayMOH300s
7807
PlayMOH300s
7810
PlayMOH300s
7814
PlayMOH300s
7848
PlayMOH300s
7851
PlayMOH300s
7852
PlayMOH300s
7860
PlayMOH300s
7896
PlayMOH300s
7899
PlayMOH300s
7903
PlayMOH300s
7912
PlayMOH300s
7917
PlayMOH300s
7925
PlayMOH300s
7929
PlayMOH300s
7939
PlayMOH300s
7957
PlayMOH300s
7969
PlayMOH300s
7976
PlayMOH300s
7977
PlayMOH300s
7978
PlayMOH300s
7979
PlayMOH300s
7980
PlayMOH300s
7981
PlayMOH300s
7985
PlayMOH300s
7995
PlayMOH300s
8004
PlayMOH300s
8018
PlayMOH300s
8050
PlayMOH300s
8057
PlayMOH300s
8070
PlayMOH300s
8080
PlayMOH300s
8090
PlayMOH300s
8096
PlayMOH300s
8097
PlayMOH300s
8105
PlayMOH300s
8106
PlayMOH300s
8107
PlayMOH300s
8108
PlayMOH300s
8109
PlayMOH300s
8112
PlayMOH300s
8115
PlayMOH300s
8116
PlayMOH300s
8123
PlayMOH300s
8133
PlayMOH300s
8144
PlayMOH300s
8155
PlayMOH300s
8164
PlayMOH300s
8172
PlayMOH300s
8173
PlayMOH300s
8174
PlayMOH300s
8179
PlayMOH300s
8183
PlayMOH300s
8189
PlayMOH300s
8193
PlayMOH300s
8194
PlayMOH300s
8202
PlayMOH300s
8207
PlayMOH300s
8215
PlayMOH300s
8221
PlayMOH300s
8226
PlayMOH300s
8227
PlayMOH300s
8236
PlayMOH300s
8237
PlayMOH300s
8248
PlayMOH300s
8274
PlayMOH300s
8277
PlayMOH300s
8280
PlayMOH300s
8285
PlayMOH300s
8290
PlayMOH300s
8291
PlayMOH300s
8292
PlayMOH300s
8293
PlayMOH300s
8304
PlayMOH300s
8307
PlayMOH300s
8308
PlayMOH300s
8309
PlayMOH300s
8318
PlayMOH300s
8327
PlayMOH300s
8330
PlayMOH300s
8338
PlayMOH300s
8339
PlayMOH300s
8342
PlayMOH300s
8350
PlayMOH300s
8394
PlayMOH300s
8395
PlayMOH300s
8396
PlayMOH300s
8397
PlayMOH300s
8398
PlayMOH300s
8399
PlayMOH300s
8421
PlayMOH300s
8422
PlayMOH300s
8440
PlayMOH300s
8449
PlayMOH300s
8462
PlayMOH300s
8463
PlayMOH300s
8464
PlayMOH300s
8475
PlayMOH300s
8482
PlayMOH300s
8485
PlayMOH300s
8490
PlayMOH300s
8500
PlayMOH300s
8506
PlayMOH300s
8509
PlayMOH300s
8510
PlayMOH300s
8528
PlayMOH300s
8543
PlayMOH300s
8544
PlayMOH300s
8549
PlayMOH300s
8550
PlayMOH300s
8551
PlayMOH300s
8558
PlayMOH300s
8580
PlayMOH300s
8581
PlayMOH300s
8582
PlayMOH300s
8583
PlayMOH300s
8593
PlayMOH300s
8613
PlayMOH300s
8628
PlayMOH300s
8629
PlayMOH300s
8635
PlayMOH300s
8656
PlayMOH300s
8657
PlayMOH300s
8668
PlayMOH300s
8669
PlayMOH300s
8686
PlayMOH300s
8700
PlayMOH300s
8706
PlayMOH300s
8707
PlayMOH300s
8742
PlayMOH300s
8745
PlayMOH300s
8754
PlayMOH300s
8763
PlayMOH300s
8764
PlayMOH300s
8765
PlayMOH300s
8766
PlayMOH300s
8771
PlayMOH300s
8772
PlayMOH300s
8789
PlayMOH300s
8790
PlayMOH300s
8793
PlayMOH300s
8794
PlayMOH300s
8797
PlayMOH300s
8806
PlayMOH300s
8814
PlayMOH300s
8815
PlayMOH300s
8816
PlayMOH300s
8817
PlayMOH300s
8820
PlayMOH300s
8826
PlayMOH300s
8827
PlayMOH300s
8828
PlayMOH300s
8829
PlayMOH300s
8839
PlayMOH300s
8844

In [31]:
df.loc[1228:1258]

,Contact Session ID,EP Name,Flow Name,Activity Name,Activity Start Timestamp,Queue Name,Agent Name,Termination Reason,hour
1228,06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45,Pre-Legal Menu Seniors Menu Telephony EP,NaN,SuburbsOrCityMenu,2025-01-14 13:12:51,NaN,NaN,NaN,13
1229,06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45,Pre-Legal Menu Seniors Menu Telephony EP,NaN,SuburbanSeniorsMenu,2025-01-14 13:13:09,NaN,NaN,NaN,13
1230,06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45,NaN,Queues,NaN,2025-01-14 13:14:48,NaN,NaN,NaN,13
1231,06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45,All LAC Queues Telephony EP,NaN,GetLoggedInSubSeniorOtherAgents,2025-01-14 13:14:48,NaN,NaN,NaN,13
1232,06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45,All LAC Queues Telephony EP,NaN,SubSeniorPreQueueMessage1_1,2025-01-14 13:14:48,NaN,NaN,NaN,13
1233,06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45,All LAC Queues Telephony EP,NaN,SubSeniorOtherQueue,2025-01-14 13:15:54,NaN,NaN,NaN,13
1234,06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45,NaN,NaN,NaN,2025-01-14 13:15:54,SubSenior Other,NaN,NaN,13
1235,06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45,All LAC Queues Telephony EP,NaN,NaN,2025-01-14 13:15:54,NaN,NaN,NaN,13
1236,06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45,All LAC Queues Telephony EP,NaN,NaN,2025-01-14 13:15:54,SubSenior Other,NaN,NaN,13
1237,06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45,All LAC Queues Telephony EP,NaN,PreQueueMessage2,2025-01-14 13:15:54,NaN,NaN,NaN,13
1238,06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45,All LAC Queues Telephony EP,NaN,PlayMOH300s,2025-01-14 13:16:06,NaN,NaN,NaN,13
1239,06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45,All LAC Queues Telephony EP,NaN,QueueMenu1,2025-01-14 13:21:07,NaN,NaN,NaN,13
1240,06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45,All LAC Queues Telephony EP,NaN,PlayMOH300s,2025-01-14 13:21:28,NaN,NaN,NaN,13
1241,06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45,All LAC Queues Telephony EP,NaN,QueueMenu1,2025-01-14 13:26:29,NaN,NaN,NaN,13
1242,06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45,All LAC Queues Telephony EP,NaN,PlayMOH300s,2025-01-14 13:26:50,NaN,NaN,NaN,13
1243,06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45,All LAC Queues Telephony EP,NaN,NaN,2025-01-14 13:29:24,SubSenior Other,Flora Fell,NaN,13
1244,06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45,All LAC Queues Telephony EP,NaN,LegalServerScreenPop,2025-01-14 13:29:25,NaN,NaN,NaN,13
1245,06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45,All LAC Queues Telephony EP,NaN,ScreenPopProcessComplete,2025-01-14 13:29:25,NaN,NaN,NaN,13
1246,06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45,All LAC Queues Telephony EP,NaN,NaN,2025-01-14 13:29:39,SubSenior Other,Flora Fell,NaN,13
1247,06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45,All LAC Queues Telephony EP,NaN,NaN,2025-01-14 13:29:39,SubSenior Other,NaN,NaN,13
1248,06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45,All LAC Queues Telephony EP,NaN,PlayMOH300s,2025-01-14 13:29:39,NaN,NaN,NaN,13
1249,06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45,All LAC Queues Telephony EP,NaN,NaN,2025-01-14 13:31:59,SubSenior Other,Flora Fell,NaN,13
1250,06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45,All LAC Queues Telephony EP,NaN,LegalServerScreenPop,2025-01-14 13:32:00,NaN,NaN,NaN,13
1251,06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45,All LAC Queues Telephony EP,NaN,ScreenPopProcessComplete,2025-01-14 13:32:00,NaN,NaN,NaN,13
1252,06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45,All LAC Queues Telephony EP,NaN,NaN,2025-01-14 13:32:05,SubSenior Other,Flora Fell,NaN,13
1253,06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45,All LAC Queues Telephony EP,NaN,NaN,2025-01-14 13:39:29,SubSenior Other,Flora Fell,NaN,13
1254,06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45,NaN,NaN,NaN,2025-01-14 13:39:29,SubSenior Other,Flora Fell,NaN,13
1255,06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45,NaN,NaN,NaN,2025-01-14 13:39:39,SubSenior Other,Flora Fell,NaN,13
1256,06ec77e5-5171-47fa-aee7-2ad42720de03,Main Number Telephony EP,NaN,NaN,2025-01-14 12:44:58,NaN,NaN,NaN,12
1257,06ec77e5-5171-47fa-aee7-2ad42720de03,NaN,LACMain,NaN,2025-01-14 12:44:58,NaN,NaN,NaN,12
1258,06ec77e5-5171-47fa-aee7-2ad42720de03,NaN,PreLegalMenuSeniorsMenu,NaN,2025-01-14 12:44:58,NaN,NaN,NaN,12

In [20]:
temp.loc[4:10]

,index,Contact Session ID,EP Name,Flow Name,Activity Name,Activity Start Timestamp,Queue Name,Agent Name,Termination Reason,hour
4,1240,06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45,All LAC Queues Telephony EP,NaN,PlayMOH300s,2025-01-14 13:21:28,NaN,NaN,NaN,13
5,1241,06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45,All LAC Queues Telephony EP,NaN,QueueMenu1,2025-01-14 13:26:29,NaN,NaN,NaN,13
6,1242,06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45,All LAC Queues Telephony EP,NaN,PlayMOH300s,2025-01-14 13:26:50,NaN,NaN,NaN,13
7,1248,06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45,All LAC Queues Telephony EP,NaN,PlayMOH300s,2025-01-14 13:29:39,NaN,NaN,NaN,13
8,1743,093223fc-33fe-48f0-aa19-f65535bfaec8,All LAC Queues Telephony EP,NaN,PlayMOH300s,2025-01-14 15:20:03,NaN,NaN,NaN,15
9,1744,093223fc-33fe-48f0-aa19-f65535bfaec8,All LAC Queues Telephony EP,NaN,QueueMenu1,2025-01-14 15:25:04,NaN,NaN,NaN,15
10,2331,0bfab117-b496-45c8-9ead-31a176aa6a95,All LAC Queues Telephony EP,NaN,PlayMOH300s,2025-01-13 08:24:19,NaN,NaN,NaN,8

In [6]:
df['Flow Name'].value_counts()

Flow Name
LACMain                    438461
PreLegalMenuSeniorsMenu    114943
LegalMenu                  103845
Queues                      60361
ClosedQueueMenu             50752
LegalFamilyMenu             25085
FarmworkerMain              21376
ClosedHoursHolidaysMenu     21290
LegalHousingMenu            19875
OtherLegalMenu              14880
Intake_Outdial               9126
CourtesyCallback             8930
LegalBenefitsMenu            7259
LegalEmploymentMenu          4559
LegalImmigrationMenu         3616
LegalHIVMenu                 2174
Name: count, dtype: int64