### CAR Data

In [27]:
# Importing relevant libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
from datetime import datetime

import warnings
warnings.filterwarnings("ignore")

In [28]:
data_path = "/Users/katherineyang/Documents/GitHub/STAT390/CAR_-_EP_Flow_Activity_Queue__Agent_Names"

### Reading all filenames in the data folder

In [29]:
folder = Path(data_path)
files = sorted(list(folder.glob("*.csv")) + list(folder.glob("*.xlsx")))
df_main = pd.DataFrame(columns=['Contact Session ID', 'EP Name', 'Flow Name', 'Activity Name', 'Activity Start Timestamp', 
                                'Queue Name', 'Agent Name', 'Termination Reason'])
df_main

Empty DataFrame
Columns: [Contact Session ID, EP Name, Flow Name, Activity Name, Activity Start Timestamp, Queue Name, Agent Name, Termination Reason]
Index: []

In [30]:
i=0
for f in files:
    i = i + 1
    if f.suffix.lower() == ".csv":
        df = pd.read_csv(f, header=2, dtype=str, engine="python", skip_blank_lines=False)
    else:  # .xlsx
        df = pd.read_excel(f, sheet_name=0, header=2, dtype=str)
    df_main = pd.concat([df_main, df], ignore_index=True)
    # print(i, f.stem, df.shape)

In [31]:
df_main["Activity Start Timestamp"] = df_main["Activity Start Timestamp"].apply(
    lambda x: datetime.strptime(x, "%Y/%m/%d %I:%M:%S %p"))

In [32]:
# Checking the datatype of all columns
df_main.dtypes

Contact Session ID                  object
EP Name                             object
Flow Name                           object
Activity Name                       object
Activity Start Timestamp    datetime64[ns]
Queue Name                          object
Agent Name                          object
Termination Reason                  object
dtype: object

In [33]:
# Creating a new column 'hour' as it will be useful to visualize peak calling hours
df_main["hour"] = df_main["Activity Start Timestamp"].dt.hour

In [34]:
df_main.head()

,Contact Session ID,EP Name,Flow Name,Activity Name,Activity Start Timestamp,Queue Name,Agent Name,Termination Reason,hour
0,001a3748-8d50-4550-8461-33547983deb0,Main Number Telephony EP,NaN,NaN,2025-01-14 12:39:32,NaN,NaN,NaN,12
1,001a3748-8d50-4550-8461-33547983deb0,NaN,LACMain,NaN,2025-01-14 12:39:32,NaN,NaN,NaN,12
2,001a3748-8d50-4550-8461-33547983deb0,Main Number Telephony EP,NaN,LanguageSelectionMenu,2025-01-14 12:39:32,NaN,NaN,NaN,12
3,001a3748-8d50-4550-8461-33547983deb0,Main Number Telephony EP,LACMain,NaN,2025-01-14 12:39:32,NaN,NaN,NaN,12
4,001a3748-8d50-4550-8461-33547983deb0,Main Number Telephony EP,NaN,MainMenu,2025-01-14 12:39:45,NaN,NaN,NaN,12

In [35]:
output_path = "/Users/katherineyang/Downloads/CAR_data.csv"
df_main.to_csv(output_path, index=False)

# Open Finder to the folder where the file was saved
import subprocess
subprocess.run(["open", "-R", output_path])

CompletedProcess(args=['open', '-R', '/Users/katherineyang/Downloads/CAR_data.csv'], returncode=0)