Author: Krish

In [392]:
# Importing relevant libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
from datetime import datetime

import warnings
warnings.filterwarnings("ignore")

### User input required
Put the data path on your system in the cell below

In [393]:
data_path = "/Users/viviadams/Downloads/CAR_-_EP_Flow_Activity_Queue__Agent_Names"

### User input ends

### Reading all filenames in the data folder

In [394]:
folder = Path(data_path)
files = sorted(list(folder.glob("*.csv")) + list(folder.glob("*.xlsx")))
df_main = pd.DataFrame(columns=['Contact Session ID', 'EP Name', 'Flow Name', 'Activity Name', 'Activity Start Timestamp', 
                                'Queue Name', 'Agent Name', 'Termination Reason'])
df_main

Empty DataFrame
Columns: [Contact Session ID, EP Name, Flow Name, Activity Name, Activity Start Timestamp, Queue Name, Agent Name, Termination Reason]
Index: []

### Reading all data files
The code chunk below reads and appends all the CAR data files. The first two rows of each file are blank and thus ignored.

In [395]:
i=0
for f in files:
    i = i + 1
    if f.suffix.lower() == ".csv":
        df = pd.read_csv(f, header=2, dtype=str, engine="python", skip_blank_lines=False)
    else:  # .xlsx
        df = pd.read_excel(f, sheet_name=0, header=2, dtype=str)
    df_main = pd.concat([df_main, df], ignore_index=True)
    print(i, f.stem, df.shape)

1 CAR - EP, Flow, Activity, Queue, & Agent Names (01-12-25 - 01-18-25) (52010, 7)
2 CAR - EP, Flow, Activity, Queue, & Agent Names (01-19-25 - 02-01-25) (95495, 7)
3 CAR - EP, Flow, Activity, Queue, & Agent Names (02-02-25 - 02-15-25) (90056, 7)
4 CAR - EP, Flow, Activity, Queue, & Agent Names (02-16-25 - 03-01-25) (88186, 7)
5 CAR - EP, Flow, Activity, Queue, & Agent Names (03-02-25 - 03-15-25) (86377, 7)
6 CAR - EP, Flow, Activity, Queue, & Agent Names (04-07-24 - 04-20-24) (88766, 7)
7 CAR - EP, Flow, Activity, Queue, & Agent Names (04-21-24 - 05-04-24) (89643, 7)
8 CAR - EP, Flow, Activity, Queue, & Agent Names (05-05-24 - 05-18-24) (82575, 7)
9 CAR - EP, Flow, Activity, Queue, & Agent Names (05-19-24 - 06-01-24) (71103, 7)
10 CAR - EP, Flow, Activity, Queue, & Agent Names (06-02-24 - 06-15-24) (84354, 7)
11 CAR - EP, Flow, Activity, Queue, & Agent Names (06-16-24 - 06-29-24) (82124, 7)
12 CAR - EP, Flow, Activity, Queue, & Agent Names (06-30-24 - 07-13-24) (79752, 7)
13 CAR - EP, Flow, Activity, Queue, & Agent Names (07-14-24 - 07-27-24) (85110, 7)
14 CAR - EP, Flow, Activity, Queue, & Agent Names (07-28-24 - 08-10-24) (84627, 7)
15 CAR - EP, Flow, Activity, Queue, & Agent Names (08-11-24 - 08-24-24) (91622, 7)
16 CAR - EP, Flow, Activity, Queue, & Agent Names (08-24-24 - 09-07-24) (90040, 7)
17 CAR - EP, Flow, Activity, Queue, & Agent Names (09-08-24 - 09-21-24) (96581, 7)
18 CAR - EP, Flow, Activity, Queue, & Agent Names (09-22-24 - 10-05-24) (89446, 7)
19 CAR - EP, Flow, Activity, Queue, & Agent Names (10-06-24 - 10-19-24) (81700, 7)
20 CAR - EP, Flow, Activity, Queue, & Agent Names (10-20-24 - 11-02-24) (88430, 7)
21 CAR - EP, Flow, Activity, Queue, & Agent Names (11-03-24 - 11-16-24) (81614, 7)
22 CAR - EP, Flow, Activity, Queue, & Agent Names (11-17-24 - 11-30-24) (66216, 7)
23 CAR - EP, Flow, Activity, Queue, & Agent Names (12-01-24 - 12-14-24) (92220, 7)
24 CAR - EP, Flow, Activity, Queue, & Agent Names (12-15-24 - 12-28-24) (62143, 7)
25 CAR - EP, Flow, Activity, Queue, & Agent Names (12-29-24 - 01-11-25) (75356, 7)
26 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 3-16 to 3-22-25 (45326, 8)
27 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 3-30 to 4-5-25 (45072, 8)
28 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 4-13 to 4-19-25 (41088, 8)
29 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 4-20 to 4-26-25 (46686, 8)
30 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 4-27 to 5-3-25 (44169, 8)
31 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 4-6 to 4-12-25 (46630, 8)
32 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 5-11 to 5-17-25 (43268, 8)
33 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 5-18 to 5-24-25 (45104, 8)
34 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 5-25 to 5-31-25 (36851, 8)
35 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 5-4 to 5-10-25 (43955, 8)
36 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 6-1 to 6-7-25 (44523, 8)
37 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 6-15 to 6-21-25 (37234, 8)
38 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 6-22 to 6-28-25 (45394, 8)
39 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 6-29 to 7-5-25 (38300, 8)
40 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 6-8 to 6-14-25 (46728, 8)
41 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 7-13 to 7-19-25 (45706, 8)
42 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 7-20 to 7-26-25 (45328, 8)
43 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 7-28 ro 8-2-25 (46237, 8)
44 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 7-6 to 7-12-25 (48707, 8)
45 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 8-10 to 8-16-25 (44095, 8)
46 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 8-17 to 8-23-25 (47062, 8)
47 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 8-24 to 8-30-25 (45113, 8)
48 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 8-3 to 8-9-25 (44706, 8)
49 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 8-31 to 9-6-25 (36177, 8)
50 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 9-7 to 9-13-25 (45304, 8)
51 CAR - EP, Flow, Activity, Queue, &amp; Agent Names3-23 to 3-29-25 (47978, 8)

### Time datatype conversion
The code chunk below converts time from string to datetime datatype.

In [396]:
df_main["Activity Start Timestamp"] = df_main["Activity Start Timestamp"].apply(
    lambda x: datetime.strptime(x, "%Y/%m/%d %I:%M:%S %p"))

In [397]:
# Checking the datatype of all columns
df_main.dtypes

Contact Session ID                  object
EP Name                             object
Flow Name                           object
Activity Name                       object
Activity Start Timestamp    datetime64[ns]
Queue Name                          object
Agent Name                          object
Termination Reason                  object
dtype: object

In [398]:
# Creating a new column 'hour' as it will be useful to visualize peak calling hours
df_main["hour"] = df_main["Activity Start Timestamp"].dt.hour

## Checking Examples of Call Journeys

### Checking for 'No Activity'

In [399]:
# From this list, can be seen that 'No activity' is not an activity name present in the dataset 
df_main['Activity Name'].unique()

array([nan, 'LanguageSelectionMenu', 'MainMenu', 'SeniorsMenu',
       'LegalMenu1', 'LegalMenu2', 'EmploymentMenu', 'ClosedQueueMenu',
       'FamilyMenu', 'OtherLegalMenu', 'OtherLegalOtherMenu',
       'SeniorsConfirmationMenu', 'SuburbsOrCityMenu', 'SeniorsADAPTMenu',
       'HousingMenu', 'PreTenantMenu', 'TenantMenu',
       'DivorceOrParentingMenu', 'ClinicVoicemailTransfer',
       'DisconnectContact', 'SetCallerID', 'BenefitsMenu',
       'FarmworkerMainMenu', 'FrontDeskTransfer1',
       'HelpWithLegalorOtherReasonMenu', 'StaffDirectoryEnglishTransfer',
       'AppointmentMenu', 'FrontDeskTransfer2',
       'ComplimentOrComplaintMenu', 'OtherLegalCriminalCaseMenu',
       'OtherLegalPersonalInjuryMenu', 'ClosedMenu', 'DisconnectContact1',
       'GetLoggedInConsumerAgents', 'IntakePreQueueMessage1',
       'ConsumerQueue', 'PreQueueMessage2', 'PlayMOH300s', 'QueueMenu1',
       'ReadANI', 'CCB', 'PlayCCBConfirmation', 'CallbackRetry',
       'AddressFaxHoursMenu', 'CriminalRecordsVoicemailTransfer',
       'StaffDirectorySpanishTransfer', 'ImmigrationMenu', 'HIVMenu',
       'SuburbanSeniorsMenu', 'GetLoggedInSubSeniorHomeownerSPAgents',
       'SubSeniorPreQueueMessage1_1', 'SubSeniorHomeownerSPQueue',
       'LegalServerScreenPop', 'SimpleDivorceMenu',
       'GetLoggedInSubSeniorOtherAgents', 'SubSeniorOtherQueue',
       'ScreenPopProcessComplete', 'SeniorNotCookCoMenu',
       'ThankYouGoodbye', 'GetLoggedInSubSeniorHomeownerAgents',
       'SubSeniorHomeownerQueue', 'FrontDeskTransfer',
       'GetLoggedInFamilySPAgents', 'FamilySPQueue',
       'TenantDeterrenceMenu', 'GetLoggedInSubSeniorTenantAgents',
       'GetLoggedInSubSeniorConsumerAgents', 'SubSeniorConsumerQueue',
       'CollectCallbackNumber', 'ConfirmCallbackNumber',
       'GetLoggedInFamilyAgents', 'FamilyQueue', 'ImmigrationOtherMenu',
       'GetLoggedInSubSeniorBenefitsSPAgents', 'HIVVoicemailTransfer',
       'ChildSupportMenu', 'GetLoggedInBenefitsAgents', 'BenefitsQueue',
       'TraffickingVoicemailTransfer', 'GetLoggedInADAPTAgents',
       'ADAPTQueue', 'SubSeniorTenantQueue', 'DisconnectContact2',
       'WorkersCompMenu', 'GetLoggedInSubSeniorEmploymentSPAgents',
       'FrontDeskTransfer3', 'GetLoggedInSubSeniorBenefitsAgents',
       'GetLoggedInBenefitsSubSeniorsAgents',
       'SubSeniorPreQueueMessage1_2', 'BenefitsSubSeniorsQueue',
       'GetLoggedInEmploymentAgents', 'EmploymentQueue',
       'GetLoggedInSubSeniorFamilyAgents', 'SubSeniorFamilyQueue',
       'GetLoggedInHousingAgents', 'HousingQueue',
       'GetLoggedInBenefitsSPAgents', 'SubSeniorBenefitsQueue',
       'DisconnectCallbackContact', 'VeteransBenefitsVoicemailTransfer',
       'BenefitsSPQueue', 'GetLoggedInSubSeniorTenantSPAgents',
       'SubSeniorTenantSPQueue', 'GetLoggedInImmigrationSPAgents',
       'ImmigrationSPQueue', 'GetLoggedInSubSeniorADAPTAgents',
       'SubSeniorADAPTQueue', 'GetLoggedInSubSeniorEmploymentAgents',
       'SubSeniorEmploymentQueue', 'GetLoggedInSubSeniorOtherSPAgents',
       'SubSeniorOtherSPQueue', 'GetLoggedInConsumerSPAgents',
       'ConsumerSPQueue', 'GetLoggedInHousingSubSeniorsAgents',
       'GetLoggedInConsumerSubSeniorsAgents', 'HolidayPrompt',
       'GetLoggedInSubSeniorFamilySPAgents',
       'GetLoggedInSubSeniorConsumerSPAgents',
       'GetLoggedInEmploymentSPAgents',
       'GetLoggedInFamilySubSeniorsAgents', 'EmploymentSPQueue',
       'SubSeniorConsumerSPQueue', 'GetLoggedInSubSeniorADAPTSPAgents',
       'GetLoggedInEducationAgents', 'EducationQueue',
       'GetLoggedInImmigrationAgents', 'ImmigrationQueue',
       'SubSeniorBenefitsSPQueue', 'GetLoggedInADAPTSPAgents',
       'ADAPTSPQueue', 'GetLoggedInADAPTSubSeniorsAgents',
       'ADAPTSubSeniorsQueue', 'GetLoggedInHousingSPAgents',
       'HousingSPQueue', 'SubSeniorFamilySPQueue',
       'MigrantVoicemailTransfer', 'SubSeniorEmploymentSPQueue',
       'GetLoggedInOtherSubSeniorsAgents',
       'GetLoggedInEmploymentSubSeniorsAgents',
       'GetLoggedInHomeownerSubSeniorsAgents', 'HomeownerSubSeniorsQueue',
       'FamilySubSeniorsQueue', 'GetLoggedInOtherSubSeniorsSPAgents',
       'OtherSubSeniorsSPQueue', 'GetLoggedInBenefitsSubSeniorsSPAgents',
       'BenefitsSubSeniorsSPQueue', 'ConsumerSubSeniorsQueue',
       'EmploymentSubSeniorsQueue',
       'GetLoggedInHousingSubSeniorsSPAgents', 'HousingSubSeniorsSPQueue',
       'GetLoggedInFamilySubSeniorsSPAgents', 'FamilySubSeniorsSPQueue',
       'OtherSubSeniorsQueue', 'GetLoggedInConsumerSubSeniorsSPAgents',
       'HousingSubSeniorsQueue', 'GetLoggedInEducationSPAgents',
       'EducationSPQueue', 'SubSeniorADAPTSPQueue',
       'GetLoggedInADAPTSubSeniorsSPAgents', 'ADAPTSubSeniorsSPQueue',
       'ConsumerSubSeniorsSPQueue', 'PlayErrorMessage',
       'GetLoggedInEmploymentSubSeniorsSPAgents',
       'EmploymentSubSeniorsSPQueue', 'TransferToSafeHaven'], dtype=object)

### Finding the Activity Name Anywhere in the Call Journey

In [400]:
# Filtering the dataframe for rows with a specified value as the acivity name
screen_pop = df_main.loc[df_main['Activity Name'] == 'LegalServerScreenPop','Contact Session ID']

# Finding all the contact session ids for those calls
screen_pop_cals = df_main.loc[df_main['Contact Session ID'].isin(screen_pop), :]

In [401]:
# Unique contact session IDs for those values 
screen_pop_cals['Contact Session ID'].unique()

array(['04617841-2326-4535-bd4c-a9954f1cf4d7',
       '06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45',
       '07f88374-f76b-4b0a-819e-0de67976e69a', ...,
       '289669ce-eab1-4a70-9aee-9eb7362642a2',
       'da2bb927-df57-46c7-9a34-0e973c62fd3f',
       '08c24ff8-835b-4005-b866-29e21116d83f'], dtype=object)

In [402]:
# Example of call journey
    # Final five rows only shown to avoid excessive output 
df_main.loc[df_main['Contact Session ID'] == '06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45', :].tail()

,Contact Session ID,EP Name,Flow Name,Activity Name,Activity Start Timestamp,Queue Name,Agent Name,Termination Reason,hour
1251,06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45,All LAC Queues Telephony EP,NaN,ScreenPopProcessComplete,2025-01-14 13:32:00,NaN,NaN,NaN,13
1252,06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45,All LAC Queues Telephony EP,NaN,NaN,2025-01-14 13:32:05,SubSenior Other,Flora Fell,NaN,13
1253,06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45,All LAC Queues Telephony EP,NaN,NaN,2025-01-14 13:39:29,SubSenior Other,Flora Fell,NaN,13
1254,06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45,NaN,NaN,NaN,2025-01-14 13:39:29,SubSenior Other,Flora Fell,NaN,13
1255,06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45,NaN,NaN,NaN,2025-01-14 13:39:39,SubSenior Other,Flora Fell,NaN,13

### Finding the Activity Name as Final Activity in Call Journey

In [403]:
# Sorting dataframe by contact session ID and time of each step in call 
sorted_df = df_main.sort_values(["Contact Session ID", "Activity Start Timestamp"])

# Finding rows with non-null activity names
df_nonnull = sorted_df[sorted_df["Activity Name"].notna()]

# Findng the last non-null activity names for each contact session ID 
last_activities = df_nonnull.groupby("Contact Session ID").tail(1)

# Filtering for calls with a specified final activity name 
target = "ScreenPopProcessComplete"
result = last_activities[last_activities["Activity Name"] == target]

# Finding the unique contact session IDs 
session_ids = result["Contact Session ID"].unique()

In [404]:
session_ids

array(['0095d75b-7e36-43bd-90a9-965e3c4722ed',
       '00d7e8e4-863b-41ce-ad69-2609bfe799de',
       '014de6cb-f912-4c78-8e3e-dd5288af51eb',
       '0223c263-3afa-4df6-856f-598d90911f40',
       '02400a1b-c865-4c86-928e-67a0ba56e1f1',
       '025170b2-34d9-4a9d-95a0-51d86f655ef6',
       '02919651-06be-46fa-a421-59ffe7e56976',
       '02ac8ff0-514f-4afe-9649-29d223372fb0',
       '02fdff16-ce55-4761-b5ef-29e128e6efe4',
       '030e4410-1c23-4904-82fe-a1b4befa5eda',
       '033a06b1-e00a-4864-963e-0305aec097ac',
       '03d381c2-5e4a-4b70-ad8d-a07b0e9f1379',
       '03fe93c3-22e5-4bd3-bb0d-339f53ba9012',
       '04a514cd-381f-48ba-b696-57ae0cf43dac',
       '0576f2ec-3db3-4c6b-8f7f-af40cb63f105',
       '05cc2e4b-f749-474e-b975-0c4b0d27319b',
       '05e6b938-c8b9-4b0f-9a45-2a8accd20d94',
       '064b9b80-9e2a-4239-8369-0d8e4652b5b1',
       '0689e1e1-3c0a-4bbe-b5cb-d9181fd86c62',
       '068b691a-edea-4631-8497-9851370b1483',
       '06d5e9b7-9b3d-4a8a-9d50-7dfd63acaf45',
       '06efa06b-9d47-456c-88ce-27fa971e8ee3',
       '0854c87e-ecfe-4959-b2a7-4b9079b24a87',
       '08c12aab-b083-474b-b47a-1d895dd15352',
       '08c24ff8-835b-4005-b866-29e21116d83f',
       '08e42a23-e82e-4e28-93eb-5d0ea25d2683',
       '092c959c-e5d5-4cb3-9662-1e0ce6933baa',
       '09b6739a-533f-4f73-91a1-2e13a1f97183',
       '0a5116fe-e4f6-43ba-9b00-5c720f42a011',
       '0a8ca32b-d325-49e5-b1a5-3fea16ca121d',
       '0a9c6249-40c5-49d6-bc27-2f179ac07b36',
       '0b5e04df-a68c-4025-8318-1d3d53e46e47',
       '0b8c159f-9faf-4adc-aafd-49ad488780ec',
       '0bed9c29-ad8f-417b-a4ce-493c79c55040',
       '0c4a56a6-eb7d-47f8-a3e4-dc35312da6b5',
       '0c4e1c3f-1049-4aa7-a02d-da72be8b508b',
       '0dbcf3f0-3d10-4cd1-9bdd-4622f381f4b4',
       '0f047b50-ccb5-4253-a292-dfff81d73777',
       '0f155f73-8908-4b4b-9729-daa3c2a63531',
       '0f7355fa-4502-4bff-bf98-93778922d593',
       '0faa7de8-50cb-4f56-8a62-1d2a287c4392',
       '1047d90b-57b5-43e6-8b64-b487ce06793d',
       '10812c80-80ad-4d93-9277-ba937bc8d7d8',
       '10bfad8f-bc06-4fbe-ad3b-d541cb6fef27',
       '117917d4-19d1-4b95-b762-da580dbabe25',
       '12cd33e5-1257-4836-90a4-7ec20b5794c1',
       '12f3ac8d-d6ec-41c5-a5c6-d3acaf978f7a',
       '13de0550-e182-4d06-9a00-9345e38d0440',
       '1410674e-d039-49df-90cd-1ab3c9aad14c',
       '14290ff9-dcc1-437c-9a5f-bbdd63ff48e1',
       '14b69729-62bc-448e-9655-24a6c391a503',
       '14dc6a7d-af8e-4b8b-a080-1dbae4279e14',
       '14e2dc09-8cb6-4152-b5b6-d42bc7fe83fd',
       '15128eac-1c03-409f-bd03-739593241746',
       '156218ad-9ed6-474e-8325-df26f0619dbb',
       '157f221e-2f63-426d-8d9b-65026f69e630',
       '15b9b41c-0789-4a7a-b6da-a7b2c7ebe2bb',
       '165adf66-ece9-4b8a-8c91-ef39303f0974',
       '16927c97-9777-4fcd-b640-fbc89fe0fb1a',
       '172ba442-c7a7-46d0-9f37-b7b6b0f8bbb0',
       '172cd837-87de-4e75-a511-53351b0834ba',
       '175fe020-bda3-4fc5-963c-98984fef738d',
       '177b7965-90eb-4677-a210-4f240f921734',
       '17a09a78-0740-45ae-9348-ecb7ebbbca7e',
       '17af0cce-e378-42aa-b191-5c9b237fd8d0',
       '1830a86b-7d2c-4b81-8a3e-8faa369f3df7',
       '1835dad2-759e-462d-9271-03b1f909f14e',
       '1901865b-7c1f-441f-b7b4-3d89b2993f49',
       '193b093d-7ba0-495d-972a-49dc5b6fc779',
       '1958022b-b2f3-459d-9e47-a2a478a6e466',
       '1a1e9b0b-83dc-47bf-b49b-bd8e30093b96',
       '1a81e076-b8e4-4082-9c35-8eb3eb3e573d',
       '1aa003cb-f6a4-416f-8b2b-9f1e0327921c',
       '1b7d7f68-7cda-4f57-9030-99553fc8a6c6',
       '1bf89e6c-6c5e-45d8-9f70-249fed50de0f',
       '1c70e249-9d57-433f-b5ce-bad4dc3c7fd4',
       '1d0febda-e669-4646-85fc-11514fd0ba95',
       '1d2a45c0-99ab-40e1-bdf9-aa65f038378b',
       '1d5b5453-f593-48dc-b1b8-1ee8640681e5',
       '1d5ce4c2-b222-4c5b-86af-93f9078bb465',
       '1d5f22ae-9239-447b-a3c5-38d534d965d5',
       '1d85219a-feae-44ee-a70d-02294f076aec',
       '1dbd13b9-5004-42f0-a310-ea9c7aac6ebd',
       '1e8bdc09-0a6f-448d-ab31-767616b16539',
       '1f0ea630-0e09-49d7-b9c2-dd0c761d331d',
       '1f334cb9-2389-4023-ac10-bbfa1fd610cb',
       '1f93800a-65bc-44e9-b9ef-5f93d2dceb6e',
       '1fc38a40-4861-4b36-b400-1eb0172aeeb1',
       '20918dc8-ea06-4ec7-b99e-3a3ae2bab9aa',
       '20ec27f8-c8ab-4b76-a3dc-9b43ed018fe3',
       '2139bd3c-90df-49ac-b95d-07e367a05cb7',
       '2146e00f-8684-4d4c-92c8-6ceca0356bf6',
       '2199527e-82bb-4b79-9e4c-e4eb53b669e1',
       '21acc328-1c8c-4f11-ac5e-e3a6df2bf488',
       '21e54019-8425-4d70-9974-f7384116aa54',
       '2259a409-1463-4502-a8dc-d9cf3844aaef',
       '2279def3-3e53-432d-bb59-0bdde022bdc9',
       '22cadd0f-8b89-441a-ae52-d166a8a88cfd',
       '23130a5d-c8a4-45ed-be68-b5966c54e3e6',
       '23b114c8-ef6a-4d8d-bc0e-8b54cae2d3ff',
       '23e5c27b-f4c7-4967-812e-04557423afc8',
       '2416b65b-3f4d-4fc0-b3e9-b990841ec902',
       '24387ffb-5c4b-4f0c-90c6-c33ac81fbc8a',
       '24a56694-bdb0-4130-8e12-620eac139fd8',
       '24d2bd9d-2398-4359-a910-cd77e42106d8',
       '24d3c753-8064-48b1-95bc-3ca905a76d86',
       '252ac997-c944-4d6d-a1bb-495aa0e1ef07',
       '25874dea-b3ac-405c-bf8d-b8a3dc3fc3ab',
       '25e6e9dc-35d8-4692-9384-0f1355ea00b1',
       '25ec0da7-8e51-41b3-a52b-919080a72c96',
       '25f5db31-6119-440b-8340-7ca307e63e6f',
       '260d38a7-013a-488f-b359-28d8a1fe9a22',
       '265bbe34-9d57-418b-a8fe-2fd3e15ab533',
       '26efa1d5-1a51-49bd-8db3-6a60183c80cc',
       '2718a483-40af-4931-8b17-292495a79151',
       '275d8c48-b91a-44b6-8a94-0344b4e5b349',
       '27bb6f70-76fc-47cc-9be1-43ee4c24dbe1',
       '2854417f-9147-439d-8b2b-e68c435aa1da',
       '285eb5d0-197a-4343-80c9-e2fb89a1525e',
       '2906b6c7-5803-4c47-8f3f-1882773206b5',
       '29a8db1c-a825-415f-9eec-80a2a4788b6f',
       '29c56067-7582-4b88-a241-ea37cee4bff4',
       '2adb1d5a-7c3b-42a5-adf1-37e07c0586aa',
       '2ae4ffa0-c9b2-4fc4-918e-3a645de5d4a4',
       '2b8b2249-67ec-4609-82d3-db06c6c458c2',
       '2bcf9fff-dd46-4f1e-8e14-d09dd63e5e3e',
       '2c618639-098f-41a9-ac54-72f18fd25833',
       '2c62fa7c-7c0c-4460-91b8-53280ffc39d5',
       '2c79c6b9-8c5a-4513-a6e9-78dec2ec365d',
       '2d8c4c27-5a77-46aa-bba5-7cee94addaf4',
       '2da0bc22-ee5d-4dd7-8a27-26e79f47f3bb',
       '2df447f8-5e53-4837-bfbb-57280e91a1ef',
       '2eaf2984-deac-452d-91dd-91417d61af58',
       '2ed4b5b6-1ab8-48ef-ad00-bdb5d257fe02',
       '2f621b6f-10df-4b81-b9ec-4b0df39c951f',
       '2fb8765b-bb1a-4347-b6c6-d522ce9039aa',
       '2fd8b13f-509c-4162-91a4-6ef360798240',
       '301456bd-08bb-4c32-b43f-1ab8786ea0b5',
       '302d8fb1-4802-4a59-8ba8-1f68a882821a',
       '30bb2199-532f-44e8-85c9-37f64e9d270b',
       '30db94d9-13f2-46e1-bb14-b227c60b963d',
       '311fb736-51a4-4f9c-a2e9-59620107ed10',
       '316adc56-6dbf-4bb7-9082-76c16f6936d8',
       '3173596f-6e62-462a-a0d6-3376a88ee203',
       '317870df-23d1-4992-b958-4a395316c737',
       '3258cd23-45a3-4690-a1f7-6737aa120aa1',
       '325c353c-46f4-424e-bc39-28a1d19d03cb',
       '3399e0b7-fd34-4658-8360-602500fa28aa',
       '33e1c95a-b8bf-4343-8be4-a7bb327381de',
       '3417887c-9ed9-4fe2-8e3c-90f21b15b095',
       '342da1bf-4899-4523-a705-ef5d952020b9',
       '3476852d-4843-4ea0-bd04-b255147bcc2b',
       '34cedc7c-c25e-4228-990f-5d894fda8696',
       '34d15eef-2604-4f79-9679-56fabe2ebfa6',
       '352215a3-9b0a-4353-91be-3de1c1928a3b',
       '35d6f352-da1e-452b-b8a0-33cf5077cd43',
       '362b2611-d0a4-4564-b7f8-b20b55961761',
       '3632a310-2325-445b-b66a-dcb355163a21',
       '36c561a6-557b-427e-b700-53b5cb391a1c',
       '37584f8f-220c-41f0-bef9-3189ff8b33cb',
       '375b818d-fe69-4974-a21d-2c3a56d9faf0',
       '384a5fe8-e7e6-468b-953b-bb2cec6e4a65',
       '38a6cb3f-2b00-4bb0-9367-d15cf0dae798',
       '39055553-44ed-4fd0-ba54-78341222f77c',
       '3957099d-7dd6-48d2-ae5a-5f7551abf39a',
       '3a6e1416-9c85-4b2e-b186-05ea6c8af5e3',
       '3ae0e7ce-c028-4c1c-8633-29a611c898ea',
       '3b08243c-b0db-409f-95a8-6522bde5d08f',
       '3b52f6ff-47ec-45f4-a8f7-e80768503305',
       '3bb2d4fd-279e-4d04-9cd5-fb83bd0daf1f',
       '3c0589d7-48fa-45b6-ae02-472e24d9b1d8',
       '3c138d0b-564b-4d80-b060-f47d5d43c33e',
       '3c7e2a77-948f-454b-abac-64ae6d388193',
       '3cd3e64f-37fc-4a5d-b895-3dbbf113a9d8',
       '3d9c77fd-28d9-43ad-afd8-f2d5b63c4449',
       '3e65ada3-0cbc-41b8-a88a-4b24589ea70c',
       '3f27dd5c-2981-430b-9039-57e5a3b7bdd2',
       '3f3bd8a9-c09a-4edd-a586-ed07f9040040',
       '3f861458-ca60-4403-9159-c06457a7f8d5',
       '3f9d48fd-a28c-4baf-8202-a149910be4dd',
       '3fcd0c6b-9778-458a-acc7-db03180b5c0d',
       '3fd5592d-49b4-4437-8e6b-f6bf518b3c56',
       '40054979-f776-4fb2-a02a-6fb5dc5131d5',
       '4079ebdf-2d6e-4079-8264-23dffcfb85fa',
       '407daadb-0757-45c5-a1df-4648d707d49a',
       '40870412-b990-44ac-a380-14d317c3e92a',
       '40a432fc-830a-4de0-a29c-074e79394e00',
       '40d27176-b048-405e-86a7-d6ba10b43bcf',
       '410d33bd-ddd7-46d0-bcdc-ddbd7badb9fb',
       '413166d1-f166-41f0-a0fa-62779a55302a',
       '42374ff7-98b9-4195-b818-786d102d5e2c',
       '42b05a62-3408-421c-bf1f-e341893e884c',
       '42df09ab-4366-47f8-8d25-d119451a5060',
       '42f76a18-caba-4dfe-af0a-33323d3095ef',
       '42fd6846-9b31-414e-a3d1-573085129a68',
       '4314886f-2f7f-436b-bfc6-c1b501f27bbc',
       '43729207-f215-4e6d-a669-70475a30e483',
       '4467cc84-a859-4350-a31e-56d6ca73d787',
       '44744c32-e3d0-42f3-9174-ff7626c64401',
       '44ae7d6f-435e-479a-929d-97d66dcf33f2',
       '44f69199-39fa-48e2-aa0f-a11c0f82fcf2',
       '456fa661-b4d0-40d7-a8de-3362ee1a9b02',
       '4591af21-db3e-4342-829c-78d5db09ba89',
       '47624907-51fd-4857-af0b-c192386a0c19',
       '47c2a70a-f39c-4566-a86e-82b103237c30',
       '47ec63ad-e728-48f7-82a3-83a225b9c0fa',
       '483d995b-abdf-494e-b5ed-a83ef5a726c5',
       '49435a44-0892-4434-a96b-cf612129fa10',
       '4a3b649e-abd8-45ea-91f0-bdc487088eea',
       '4a864363-4159-4a68-8053-6c46196d692d',
       '4a988769-d373-4dd7-9418-fde580f88fb2',
       '4b3fcd32-f79a-4bc3-aab5-bb7b26734031',
       '4bc32fc4-7cf5-4e0a-96a1-f86ed2b0b73c',
       '4bd75aa5-f8bd-46df-aa73-672ed5c9a950',
       '4be8df02-7842-4209-a276-4abd7aecc2dc',
       '4c56d16c-289f-4d74-884c-ec3693e63349',
       '4c92faa7-f1fc-4f9a-8353-809cb4f1840c',
       '4cf01a30-4365-4034-9839-38c27c3ffddd',
       '4d1afc31-c512-424a-a1ba-8a25d70121f1',
       '4e7593e1-f2b3-4fc5-b195-d70580de85a8',
       '4ec55a79-7405-4aeb-a153-cc67928b6ff7',
       '4ee41cc2-ebfe-41cd-a371-8c97ba7402b5',
       '4f014b25-c922-4731-a8f5-b4eabf8d3f7b',
       '4f9f9520-b660-43d1-928d-071543c415da',
       '4fb18265-2b8b-4c22-b9c2-970611e52e91',
       '4fb33f87-f76f-4938-9fa7-8d88b1c3e349',
       '4ff7c874-f74e-475c-8ffe-816dd03425a6',
       '50782a05-0de4-4f13-a4e7-ca8b0b5a5a7b',
       '5153793b-f8cd-4281-8ae4-9277c3271c58',
       '51cde949-7d8f-4f0a-be8c-fdcf3ff8e51e',
       '525bf485-f863-4e6a-acff-b1795a285769',
       '52934e7f-d75c-4c49-997d-0f414be3fd04',
       '52db4ce0-14a6-4ccd-8987-fda651b74db8',
       '53216d62-90a2-48c4-9d45-0ef3b33f6f8c',
       '53954475-e0d5-41c6-975a-335437114bc4',
       '539b0d02-2e48-417f-bec5-c6543b6647c8',
       '53d4b21d-f954-4304-b1e0-baf6cdded9ee',
       '53ebd1d8-5c09-4fca-b555-995aea383f52',
       '53ed92a1-0786-43d9-b393-8ec493830348',
       '543bdcab-2fa7-415f-8a6f-fd60f17a68d8',
       '553e6026-de08-4354-93f2-d4de793667db',
       '56fe44d9-bfa0-4e32-93b0-f922a2dbdd43',
       '5722b30c-5e26-4110-a1bb-ce93a2e0ed84',
       '57576abf-ba59-43e4-9e52-baca3714c9b3',
       '57b50da5-ddd5-467d-90fa-230c6cf79cbb',
       '5903ecc9-26b0-449b-a909-d3144d0187a3',
       '59c93eb9-73ae-4e90-9635-072e5aef4fe4',
       '5a14419b-fd0a-4f57-a15f-bcdf984d7b8f',
       '5ade9fbb-339d-426a-85f4-9a64640609ea',
       '5b381093-b91f-41a0-980d-bc2aa0e9ef7b',
       '5bd47256-ef36-4524-b20b-83604cf3ed67',
       '5be9737b-2032-4bd4-bfdf-f0dcb392b213',
       '5c0d2b7e-9304-480c-97c7-6c41b57c7443',
       '5cc37062-0e4d-42df-8e34-461bfd3a9170',
       '5d63320d-b4b6-43b9-b0a1-567279728cb2',
       '5d719fd1-46db-4e6f-99fb-c91b91dbb161',
       '5d790239-6514-470b-95b5-caed0206bc39',
       '5d9513d4-6f98-4af3-999f-cba436a2b5c1',
       '5dc47d28-e765-496f-87c0-2075755bd623',
       '5e3ae0ff-d956-428b-980f-7d037fe6bc93',
       '5e3c36e2-32c2-41bd-8fc6-0a2b978d53d7',
       '5ea69711-63ad-42af-a29e-822a1cec59e5',
       '5eac1e47-d451-4fc0-8422-d64c8dc3a9f2',
       '5eb9a76d-61e6-44a0-be81-0710fd05673a',
       '5ecba011-edad-4789-bf13-db87ee81b467',
       '5f2cef59-3090-4ff1-bec0-514c1cd0ca41',
       '5f3cca50-1438-4bc4-bf76-3167c7becccd',
       '5f466227-215f-452d-bb43-599e283fee07',
       '60478ba5-1712-43c5-ad76-bd7f14ece8ed',
       '60d81c9f-5182-45d5-b8d1-a228d45eae1a',
       '6138a449-70e4-4b66-87f0-09c0211e5075',
       '6147fe19-a679-45ea-9f2c-c7186012e3ce',
       '617878a3-30d6-481c-aef1-182159395ac4',
       '617f19e6-ac2b-49a7-945d-24f9d8abd79f',
       '6221f21c-b577-475d-8997-059a041269b7',
       '626d95d5-1ca7-4b82-adf2-d314197db02b',
       '6279c068-b5bc-415c-923e-7633e0cd1bcd',
       '631bc58b-7313-4f83-b262-a845f1753e14',
       '63316936-99ba-4a79-ba22-110cfe4c239c',
       '63f2e100-15af-4b88-8102-4351c71a38ae',
       '63fe5730-cfad-49ec-a87b-3b9b42817086',
       '64b1a65f-db30-4c41-967a-a1b99e22c6ec',
       '64ca0ec2-4aa1-4be3-b130-4703533237ba',
       '64ce815f-4a8a-4e59-a596-c93ff76612f8',
       '64e3b190-1ece-479b-8174-15591c82066b',
       '64ec102a-3d4d-4088-b0b7-bcf37daef637',
       '65119bbf-0916-4b38-839e-b1115d53e7bd',
       '65263e56-3275-4154-9927-ed64ab39e963',
       '66818376-d8cd-4ae0-9d84-06531a0f541c',
       '669f2676-51df-4fa1-a8a8-7fb9d048f634',
       '6906da18-a544-4842-90d1-7e1c2dd134e8',
       '6959c601-fcab-4b79-b41b-9172eef94007',
       '698456e7-b014-405d-956b-bc9997585721',
       '69a77967-2538-4112-82bd-e12a3d400aa5',
       '69fe4804-3134-4881-bd55-1500453be46f',
       '6aec6f2c-499e-42c7-8ae1-c930905b4062',
       '6aefc825-3e06-436e-9cca-ec8e62b299e6',
       '6afd7d8b-5454-4c05-8c75-aff2bf79fd49',
       '6b25a674-9af1-4bab-be76-00e1f7268828',
       '6b722a06-4b0c-481a-bb8b-9a9c8768a27a',
       '6b9190d5-c990-4626-9b85-596e58e67079',
       '6bcb4a1b-e6d3-4859-a93c-0cff387199a4',
       '6c2c9fa2-2117-467a-8f39-e54d682f53ce',
       '6ca97fd1-0e74-47ce-8963-5f11b17a45e8',
       '6d322046-b0c3-4c56-94e1-9a497e2e01e9',
       '6d7eb388-ba8f-4506-bdfe-b457c447f281',
       '6d86198a-8871-4614-b4cd-074e26310374',
       '6ddb4ef5-dba6-49cb-8206-8db78a33b391',
       '6dfc58d1-8231-4df6-baeb-493bee55de10',
       '6e962739-06b4-47f1-8966-2967d39c8904',
       '6ecb601e-fc16-4264-b571-a527c5d8090b',
       '6f10642a-c047-44e4-b609-8e1bdd845583',
       '6f526f00-3be1-45e4-a69c-9c525d02cd06',
       '6f8c8427-18fb-4c7a-977d-0fa303ed86fe',
       '7051f827-685b-48cc-a8ae-58ae69ec041a',
       '716b623b-cdf6-4d76-a620-8a30e248d4fd',
       '72e17f9a-095a-4cbd-924f-46b700eccb5f',
       '73f8d419-0b59-41a8-97ef-256de846f106',
       '741cf332-f648-4faa-a040-fef4b4084133',
       '74ccc273-3b27-41e5-a4a4-60bace0c1ca3',
       '74e94d8b-5e4d-4d88-9e75-b3f0fe400346',
       '753c136a-eb33-4087-8044-5ca4a00aaedf',
       '755614d9-0e64-4108-ac14-592c8c625783',
       '75df6824-be25-4200-80ea-6a557e6ecad5',
       '7628c073-939b-4d9c-a720-836af7e453d1',
       '76aa43d5-9d33-46ac-89ca-d9c22a27b49c',
       '7709d270-10c3-4af0-ac13-72a169cfb88f',
       '77bfc717-3d19-40ba-af6e-16cc2ad0f0f9',
       '785e628c-6bbb-44f2-ac50-b5d1a5646e59',
       '7870d1e7-b0ba-4257-8ca3-5447853ad42a',
       '787c134b-1c63-4f74-b959-d769e7c31802',
       '79097d4c-2d25-4ed2-9cdb-0d63be82b77a',
       '793665e4-ce5c-4f2a-bead-6d25c9141420',
       '79daf1b9-8c84-4814-a1a4-b9b5c9fc24b6',
       '7a09a109-2c05-465e-8663-1d58bc425d1c',
       '7ab7a89f-9679-4cc2-b8a0-d067bf384d1a',
       '7b11716b-bb2d-4f91-94e4-d29a3c658851',
       '7b15f321-3107-484f-906b-1b5a764fbc94',
       '7b51b623-8d3c-4e99-87c1-de831c39327a',
       '7c5b38fa-5fd2-4098-a411-7ad9eb0764c9',
       '7cc3dc34-4ade-469c-8b52-e10f092755a5',
       '7d0699b5-881c-4a29-84a7-32fce4ef17b0',
       '7d216217-6986-4ce8-acb6-97e821a84793',
       '7dd2aeed-6302-4af8-b460-b8088f402091',
       '7dda888f-b2b1-4c91-8fc4-12ab91d9b6d5',
       '7e81eed9-5488-4b20-ba76-fc446e45f00f',
       '7f070182-d7e6-497a-9524-8f06e5b325cc',
       '804ab03a-3efa-43a7-837b-1c6b6b9c8fc4',
       '810ea54d-9a1e-48e7-8379-d121bde081d3',
       '8116e315-49a0-4642-907f-9cf4031435a4',
       '815049fe-56d3-4b30-a9fb-9d6401679e3c',
       '8172b57f-7553-41ef-8260-683489fe2d2e',
       '8267a794-005e-4416-91c2-b521d6fe9f04',
       '8299a77d-d797-4d19-a649-8752f0c92952',
       '82d7a170-9402-4c88-862a-2f0536c293f2',
       '83388d08-5e85-40b7-95db-a8ad73cb5532',
       '83420372-eb0a-4240-acad-4f19a4314cb9',
       '83583402-1b06-4710-8829-6a3ab71db7ca',
       '835947f7-7ea5-4f8d-8ec9-01a1288e5f30',
       '84c13a3a-d86c-4f42-adff-4656482e340c',
       '85323fbf-35e4-4bb6-b12b-03c9063c3520',
       '8554c91b-0d09-447e-a23f-aae927895457',
       '85a9a064-ca43-451d-8941-e6941278b7ac',
       '85b50557-ef89-48e7-a9df-5a66f3290ea3',
       '8847f99a-1807-4d20-9e07-31f58e8c6672',
       '892436ce-4f19-4698-accd-0de10774db59',
       '8ab97427-90ee-44c3-ba3a-99bc542de925',
       '8b2e9255-5868-43be-9fdb-d403b53b73db',
       '8b80c606-e643-4e92-bd40-2246ea23aafc',
       '8bacfe8d-3d7b-4bbd-b7fa-02e0e3e605f6',
       '8bf3acbe-9ce6-4244-905e-280f3ba8708d',
       '8c6792f3-32ec-430c-8273-fed1d208401a',
       '8c6bb274-82f8-463e-8469-9e06e8f3e4ef',
       '8cc9bfa0-ba77-4491-b9b4-65608cb1ae26',
       '8cd09b51-f7b5-4153-a5b8-84982a4f713c',
       '8ce86303-3f61-4e17-abd2-5004b6703e65',
       '8d0ce8d7-aa7d-4e86-b020-9641b8de4332',
       '8d7db0fb-0d8a-4d23-bbf8-c5b958bb782e',
       '8dad16e1-e7eb-4168-8c95-1c29bc14ecba',
       '8dfc9da9-30ba-4019-abf3-5c07f2bd3cef',
       '8e983e4b-3c96-4f91-aab9-fef9df0d1e7d',
       '8ef367c7-553e-40cc-a45f-afe23bef722f',
       '8f5134fe-969f-4458-ac15-513b71dcd41e',
       '8f708daf-c402-4801-ba9c-5dc16ded2906',
       '8f9710b0-b014-48d8-8e83-cc789be19d9a',
       '8fe7db14-d3ac-4835-9e4e-c16ea9329c62',
       '8ff168d9-6478-4ee6-a7a7-4f1ec9b1cdf0',
       '90030e1b-78e6-48be-b36c-0121aac22d53',
       '9065fa74-2a92-4bed-b109-f201dec9d485',
       '90943dcb-e706-409e-a00b-b330015f1f52',
       '910b473c-2141-4d4e-ad4d-55e29d733426',
       '9158ea56-4792-46dc-bcb1-28c67374b39e',
       '91919320-4345-4344-831c-cc591f41598a',
       '91fa63a2-d99a-4cc2-aef1-df88db5fb724',
       '9231cc86-3940-4615-8787-54fbd19385e6',
       '92442df6-b305-403c-b770-e24e66475b16',
       '926e909f-98f3-4558-80a7-d3b63a399aa9',
       '9281533a-738a-4ff5-86de-5b96b153b071',
       '92dbb2b3-e4b9-4ec3-9a2e-a011140f58c3',
       '92ef00fe-f819-4a49-98d3-3629fad6998e',
       '932dcc3d-eabb-44aa-befd-bbf6dae134b8',
       '936789e1-99e6-486b-89a1-2c87b654fc99',
       '93a61461-8dcf-4036-ac3c-1db6c47e00b5',
       '93ef72da-d345-4c52-a5a3-111f2e79a823',
       '94a75433-6f4d-4ee5-827b-211596bb0d48',
       '94dd52ad-6cae-4013-a0d6-09cb8d581f57',
       '94f76fae-f20b-4a9d-af74-a0caaf62acf5',
       '954b0787-0bbb-4810-bb82-57c5e89c330d',
       '95b0b8a2-d39f-4502-a38e-9f40e8c36f86',
       '964ca45a-5ac5-43c8-a1e4-9710f5a9220d',
       '96a7fec0-8f73-4a3c-84e4-49afaabdcdf3',
       '970aabbf-887a-44c8-8470-05b3a73da0a5',
       '9722bd9c-49a1-447c-b434-15dbae78daf1',
       '9729335f-84a2-438c-80e2-219022fd9025',
       '97365b67-bc55-4fe1-a21a-0f5fca5e5e45',
       '9789d4d0-7eb6-4c2c-adbb-39aad5c6736f',
       '978f10fb-9be4-4ac2-b7b2-05b6a6f2f3ad',
       '97a27f49-6937-4588-9d28-50ca12b7216e',
       '97ffd1d9-19a5-40e4-8b5a-e3402e76cfe5',
       '982276ef-47c0-4800-be3e-8a74dcd38f06',
       '98545b3f-4689-4f87-9418-b9f2d62a9cb0',
       '98a5d3b5-018f-4e83-ab88-e87c4ef6a718',
       '98ea8159-ddf3-4d26-86ec-d7f9383fbadf',
       '9910aa76-c617-4524-a9f4-9bc36a86e326',
       '99dcaf7c-109c-4481-ad10-9514eab16421',

In [405]:
# Example of call journey
    # Final five rows only shown to avoid excessive output 
df_main.loc[df_main['Contact Session ID'] == 'ffeba08a-2298-40a2-8864-ecb0a414e7e8', :].tail()

,Contact Session ID,EP Name,Flow Name,Activity Name,Activity Start Timestamp,Queue Name,Agent Name,Termination Reason,hour
2456984,ffeba08a-2298-40a2-8864-ecb0a414e7e8,All LAC Queues Telephony EP,NaN,ScreenPopProcessComplete,2025-05-29 12:27:26,NaN,NaN,NaN,12
2456985,ffeba08a-2298-40a2-8864-ecb0a414e7e8,All LAC Queues Telephony EP,NaN,NaN,2025-05-29 12:27:30,SubSenior Benefits,Flora Fell,NaN,12
2457206,ffeba08a-2298-40a2-8864-ecb0a414e7e8,All LAC Queues Telephony EP,NaN,NaN,2025-05-29 12:40:53,SubSenior Benefits,Flora Fell,Customer Left,12
2457207,ffeba08a-2298-40a2-8864-ecb0a414e7e8,NaN,NaN,NaN,2025-05-29 12:40:53,SubSenior Benefits,Flora Fell,NaN,12
2457209,ffeba08a-2298-40a2-8864-ecb0a414e7e8,NaN,NaN,NaN,2025-05-29 12:40:55,SubSenior Benefits,Flora Fell,NaN,12

### 'GetLoggedIn<*>Agents' Examples

#### There is a termination reason and the NaN activity comes after the final activity name

In [424]:
df_main.loc[df_main['Contact Session ID'] == 'ed3e6cf0-0a99-4e23-8722-4dd064e8e29e', :].tail()

,Contact Session ID,EP Name,Flow Name,Activity Name,Activity Start Timestamp,Queue Name,Agent Name,Termination Reason,hour
2359560,ed3e6cf0-0a99-4e23-8722-4dd064e8e29e,Pre-Legal Menu Seniors Menu Telephony EP,NaN,SuburbanSeniorsMenu,2025-05-13 11:17:37,NaN,NaN,NaN,11
2359568,ed3e6cf0-0a99-4e23-8722-4dd064e8e29e,Pre-Legal Menu Seniors Menu Telephony EP,NaN,PreTenantMenu,2025-05-13 11:18:05,NaN,NaN,NaN,11
2359583,ed3e6cf0-0a99-4e23-8722-4dd064e8e29e,NaN,Queues,NaN,2025-05-13 11:18:41,NaN,NaN,NaN,11
2359584,ed3e6cf0-0a99-4e23-8722-4dd064e8e29e,All LAC Queues Telephony EP,NaN,GetLoggedInSubSeniorTenantAgents,2025-05-13 11:18:41,NaN,NaN,NaN,11
2359585,ed3e6cf0-0a99-4e23-8722-4dd064e8e29e,All LAC Queues Telephony EP,NaN,NaN,2025-05-13 11:18:41,NaN,NaN,Customer Left,11

### There is no termination reason and the NaN comes before the final activity name

In [426]:
df_main.loc[df_main['Contact Session ID'] == 'bf1b3761-0c49-47cd-b063-559739afe159', :].tail()

,Contact Session ID,EP Name,Flow Name,Activity Name,Activity Start Timestamp,Queue Name,Agent Name,Termination Reason,hour
38480,bf1b3761-0c49-47cd-b063-559739afe159,Pre-Legal Menu Seniors Menu Telephony EP,NaN,SuburbsOrCityMenu,2025-01-15 13:30:45,NaN,NaN,NaN,13
38481,bf1b3761-0c49-47cd-b063-559739afe159,Pre-Legal Menu Seniors Menu Telephony EP,NaN,SuburbanSeniorsMenu,2025-01-15 13:30:45,NaN,NaN,NaN,13
38482,bf1b3761-0c49-47cd-b063-559739afe159,Pre-Legal Menu Seniors Menu Telephony EP,NaN,PreTenantMenu,2025-01-15 13:31:16,NaN,NaN,NaN,13
38483,bf1b3761-0c49-47cd-b063-559739afe159,All LAC Queues Telephony EP,NaN,NaN,2025-01-15 13:31:50,NaN,NaN,NaN,13
38484,bf1b3761-0c49-47cd-b063-559739afe159,All LAC Queues Telephony EP,NaN,GetLoggedInSubSeniorTenantAgents,2025-01-15 13:31:50,NaN,NaN,NaN,13